create table orac_core.conversations
(
  conversation_id number generated by default on null as identity not null,
  user_id         number not null,
  session_id      varchar2(64 byte) not null,
  llm_id          number,
  title           varchar2(200 byte) default on null 'Brief exchange...',
  state           varchar2(20 byte) default 'open' not null,
  created_on      timestamp default systimestamp not null,
  created_by      varchar2(128 byte) default coalesce(
                    sys_context('apex$session', 'app_user'),
                    sys_context('userenv', 'proxy_user'),
                    sys_context('userenv', 'session_user'),
                    user
                  ) not null,
  updated_on      timestamp,
  updated_by      varchar2(128 byte),
  row_version     number default 1 not null
)
;

alter table orac_core.conversations
  add constraint conversations_cc1
  check (state in ('archived', 'closed', 'open'))
;

comment on table orac_core.conversations is 'One row per dialog thread; holds session key and default LLM.'
;

comment on column orac_core.conversations.conversation_id is 'Primary key for conversations.'
;

comment on column orac_core.conversations.session_id is 'External/session key (unique).'
;

comment on column orac_core.conversations.llm_id is 'Default LLM for this conversation; messages may override.'
;

create unique index orac_core.conversations_pk
  on orac_core.conversations
  (
    conversation_id asc
  )
;

create index orac_core.ix_conversations_llm_id
  on orac_core.conversations
  (
    llm_id asc
  )
;

create index orac_core.ix_conversations_user_id
  on orac_core.conversations
  (
    user_id asc
  )
;

create unique index orac_core.uq_conversations_session
  on orac_core.conversations
  (
    session_id asc
  )
;

alter table orac_core.conversations
  add constraint conversations_pk
  primary key (conversation_id)
;

alter table orac_core.conversations
  add constraint uq_conversations_session
  unique (session_id)
;

create table orac_core.devices
(
  device_id   varchar2(128 byte) not null,
  user_id     number not null,
  host_name   varchar2(255 byte),
  is_active   char(1 byte) default 'Y' not null,
  created_on  timestamp default on null systimestamp not null,
  created_by  varchar2(128 byte) default on null sys_context('userenv', 'session_user') not null,
  updated_on  timestamp,
  updated_by  varchar2(128 byte),
  row_version number default 1 not null
)
;

alter table orac_core.devices
  add constraint devices_ck1
  check (is_active in ('N', 'Y'))
;

create unique index orac_core.devices_pk
  on orac_core.devices
  (
    device_id asc
  )
;

create index orac_core.devices_uid_idx
  on orac_core.devices
  (
    user_id asc
  )
;

alter table orac_core.devices
  add constraint devices_pk
  primary key (device_id)
;

create table orac_core.llm_registry
(
  llm_id             number generated always as identity not null,
  name               varchar2(100 byte) not null,
  provider           varchar2(100 byte),
  model              varchar2(200 byte) not null,
  context_policy     varchar2(20 byte) not null,
  max_context_tokens number,
  is_enabled         char(1 byte) default 'Y' not null,
  properties         json,
  created_on         timestamp default on null systimestamp not null,
  created_by         varchar2(128 byte) default on null coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  updated_on         timestamp,
  updated_by         varchar2(128 byte),
  row_version        number default 1 not null
)
;

alter table orac_core.llm_registry
  add constraint llm_reg_cc1
  check (context_policy in ('app', 'external', 'hybrid', 'model', 'unresolved'))
;

alter table orac_core.llm_registry
  add constraint llm_reg_ck2
  check (is_enabled in ('N', 'Y'))
;

comment on table orac_core.llm_registry is 'Registry of available large language models (LLMs) and their configuration.'
;

comment on column orac_core.llm_registry.llm_id is 'Primary key for the orac_core.llm_registry table.'
;

comment on column orac_core.llm_registry.name is 'Human-readable unique name for the model configuration.'
;

comment on column orac_core.llm_registry.provider is 'Vendor/source of the model.'
;

comment on column orac_core.llm_registry.model is 'Provider model identifier.'
;

comment on column orac_core.llm_registry.context_policy is 'How conversation state is managed for this model.'
;

comment on column orac_core.llm_registry.max_context_tokens is 'Maximum supported context window in tokens.'
;

comment on column orac_core.llm_registry.properties is 'Free-form JSON for provider/model metadata.'
;

create unique index orac_core.uq_llm_registry_name
  on orac_core.llm_registry
  (
    name asc
  )
;

create unique index orac_core.llm_registry_pk
  on orac_core.llm_registry
  (
    llm_id asc
  )
;

alter table orac_core.llm_registry
  add constraint llm_registry_pk
  primary key (llm_id)
;

alter table orac_core.llm_registry
  add constraint uq_llm_registry_name
  unique (name)
;

create table orac_core.message_embeddings
(
  emb_id             number generated by default on null as identity not null,
  message_id         number not null,
  chunk_index        number default 1 not null,
  span_start         number,
  span_end           number,
  lossless_text      clob not null,
  content_snapshot   json,
  embedding          vector(*, *) not null,
  embedding_model    varchar2(100 char) not null,
  embedding_provider varchar2(100 char) default on null 'oracle' not null,
  distance_metric    varchar2(16 char) default 'COSINE' not null,
  tokens_used        number,
  created_on         timestamp default systimestamp not null,
  created_by         varchar2(128 char) default sys_context('userenv', 'session_user') not null,
  updated_on         timestamp,
  updated_by         varchar2(128 char),
  row_version        number default 1 not null
)
;

alter table orac_core.message_embeddings
  add constraint message_embeddings_ck1
  check (distance_metric in ('COSINE', 'DOT', 'HAMMING', 'JACCARD', 'L2', 'L2_SQUARED', 'MANHATTAN'))
;

comment on table orac_core.message_embeddings is 'Embeddings for message-level chunks.'
;

comment on column orac_core.message_embeddings.message_id is 'FK to orac_core.messages.message_id.'
;

comment on column orac_core.message_embeddings.chunk_index is '1-based ordinal of chunk within the message.'
;

create index orac_core.ix_msg_emb_message_id
  on orac_core.message_embeddings
  (
    message_id asc
  )
;

create unique index orac_core.message_embeddings_pk
  on orac_core.message_embeddings
  (
    emb_id asc
  )
;

create unique index orac_core.uq_msg_emb_message_chunk
  on orac_core.message_embeddings
  (
    message_id asc,
    chunk_index asc
  )
;

alter table orac_core.message_embeddings
  add constraint message_embeddings_pk
  primary key (emb_id)
;

alter table orac_core.message_embeddings
  add constraint uq_msg_emb_message_chunk
  unique (message_id, chunk_index)
;

create table orac_core.messages
(
  message_id      number generated by default on null as identity not null,
  conversation_id number not null,
  turn_index      number not null,
  role            varchar2(20 byte) not null,
  content         json not null,
  tokens_used     number,
  meta            json,
  llm_id          number,
  created_on      timestamp default systimestamp not null,
  created_by      varchar2(128 byte) default coalesce(
                    sys_context('apex$session', 'app_user'),
                    sys_context('userenv', 'proxy_user'),
                    sys_context('userenv', 'session_user'),
                    user
                  ) not null,
  updated_on      timestamp,
  updated_by      varchar2(128 byte),
  row_version     number default 1 not null
)
;

alter table orac_core.messages
  add constraint messages_ck1
  check (role in ('assistant', 'system', 'tool', 'user'))
;

comment on table orac_core.messages is 'Atomic utterances within a conversation (user/assistant/system/tool).'
;

comment on column orac_core.messages.turn_index is 'Ordinal per conversation starting at 1.'
;

comment on column orac_core.messages.llm_id is 'Optional override of conversation default LLM.'
;

create index orac_core.ix_messages_conv_id
  on orac_core.messages
  (
    conversation_id asc
  )
;

create index orac_core.ix_messages_llm_id
  on orac_core.messages
  (
    llm_id asc
  )
;

create unique index orac_core.messages_pk
  on orac_core.messages
  (
    message_id asc
  )
;

create unique index orac_core.uq_messages_conv_turn
  on orac_core.messages
  (
    conversation_id asc,
    turn_index asc
  )
;

alter table orac_core.messages
  add constraint messages_pk
  primary key (message_id)
;

alter table orac_core.messages
  add constraint uq_messages_conv_turn
  unique (conversation_id, turn_index)
;

create table orac_core.user_preferences
(
  pref_id     number generated by default on null as identity not null,
  user_id     number not null,
  pref_key    varchar2(100 byte) not null,
  pref_value  json,
  value_type  varchar2(8 byte) default 'string' not null,
  created_on  timestamp default on null systimestamp not null,
  created_by  varchar2(128 byte) default on null coalesce(
                sys_context('apex$session', 'app_user'),
                sys_context('userenv', 'proxy_user'),
                sys_context('userenv', 'session_user'),
                user
              ) not null,
  updated_on  timestamp,
  updated_by  varchar2(128 byte),
  row_version number default 1 not null
)
;

alter table orac_core.user_preferences
  add constraint user_preferences_ck1
  check (value_type in ('boolean', 'json', 'number', 'string'))
;

comment on table orac_core.user_preferences is 'Stores key-value preference settings for each user.'
;

comment on column orac_core.user_preferences.pref_id is 'Primary key for the preference row.'
;

comment on column orac_core.user_preferences.user_id is 'Owning user for the preference.'
;

comment on column orac_core.user_preferences.pref_key is 'Namespaced preference name scoped to a single user.'
;

comment on column orac_core.user_preferences.pref_value is 'Stored preference value.'
;

create unique index orac_core.uq_user_preferences_user_key
  on orac_core.user_preferences
  (
    user_id asc,
    pref_key asc
  )
;

create index orac_core.ix_user_prefs_uid
  on orac_core.user_preferences
  (
    user_id asc
  )
;

create unique index orac_core.user_preferences_pk
  on orac_core.user_preferences
  (
    pref_id asc
  )
;

alter table orac_core.user_preferences
  add constraint user_pref_ck1
  check
  (
    (
      value_type = 'string'
      and json_value(pref_value, '$' returning varchar2(4000) null on error) is not null
    )
    or
    (
      value_type = 'number'
      and json_value(pref_value, '$' returning number null on error) is not null
    )
    or
    (
      value_type = 'boolean'
      and lower(json_value(pref_value, '$' returning varchar2(5) null on error)) in ('true', 'false')
    )
    or
    (
      value_type = 'json'
      and json_exists(pref_value, '$')
    )
  )
;

alter table orac_core.user_preferences
  add constraint user_preferences_pk
  primary key (pref_id)
;

alter table orac_core.user_preferences
  add constraint uq_user_preferences_user_key
  unique (user_id, pref_key)
;

create table orac_core.user_prompt_elements
(
  element_id     number generated by default on null as identity not null,
  user_id        number not null,
  category_code  varchar2(50 byte) not null,
  prompt_element clob not null,
  weight_score   number(5,2) default 1 not null,
  is_enabled     char(1 byte) default 'Y' not null,
  created_on     timestamp default on null systimestamp not null,
  created_by     varchar2(128 byte) default on null sys_context('userenv', 'session_user') not null,
  updated_on     timestamp,
  updated_by     varchar2(128 byte),
  row_version    number default 1 not null
)
;

alter table orac_core.user_prompt_elements
  add constraint user_prompt_elements_ck1
  check (is_enabled in ('N', 'Y'))
;

create index orac_core.upe_user_cat_idx
  on orac_core.user_prompt_elements
  (
    user_id asc,
    category_code asc
  )
;

create unique index orac_core.user_prompt_elements_pk_idx
  on orac_core.user_prompt_elements
  (
    element_id asc
  )
;

alter table orac_core.user_prompt_elements
  add constraint user_prompt_elements_pk
  primary key (element_id)
;

create table orac_core.user_synonyms
(
  user_id     number not null,
  alias_type  varchar2(16 byte) not null,
  alias_value varchar2(256 byte) not null,
  is_active   char(1 byte) default 'Y' not null,
  created_on  timestamp default on null systimestamp not null,
  created_by  varchar2(128 byte) default on null sys_context('userenv', 'session_user') not null,
  updated_on  timestamp,
  updated_by  varchar2(128 byte),
  row_version number default 1 not null
)
;

alter table orac_core.user_synonyms
  add constraint user_synonyms_ck1
  check (is_active in ('N', 'Y'))
;

create unique index orac_core.user_synonyms_pk
  on orac_core.user_synonyms
  (
    alias_type asc,
    alias_value asc
  )
;

create index orac_core.user_synonyms_uid_idx
  on orac_core.user_synonyms
  (
    user_id asc
  )
;

alter table orac_core.user_synonyms
  add constraint user_synonyms_pk
  primary key (alias_type, alias_value)
;

create table orac_core.users
(
  user_id      number generated always as identity not null,
  username     varchar2(100 char) not null,
  display_name varchar2(200 char),
  email        varchar2(320 char),
  is_active    char(1 char) default 'Y' not null,
  created_on   timestamp default on null systimestamp not null,
  created_by   varchar2(128 char) default on null coalesce(
                 sys_context('apex$session', 'app_user'),
                 sys_context('userenv', 'proxy_user'),
                 sys_context('userenv', 'session_user'),
                 user
               ) not null,
  updated_on   timestamp,
  updated_by   varchar2(128 char),
  row_version  number default 1 not null
)
;

alter table orac_core.users
  add constraint users_ck1
  check (is_active in ('N', 'Y'))
;

comment on table orac_core.users is 'Stores registered users of the orac system.'
;

comment on column orac_core.users.user_id is 'Primary key for the orac_core.users table.'
;

comment on column orac_core.users.username is 'Unique login handle for the orac_core.users table.'
;

comment on column orac_core.users.display_name is 'Human-friendly name for the user.'
;

comment on column orac_core.users.email is 'Primary contact email for the user.'
;

create unique index orac_core.uq_users_username
  on orac_core.users
  (
    username asc
  )
;

create unique index orac_core.users_pk
  on orac_core.users
  (
    user_id asc
  )
;

alter table orac_core.users
  add constraint users_pk
  primary key (user_id)
;

alter table orac_core.users
  add constraint uq_users_username
  unique (username)
;

alter table orac_core.conversations
  add constraint fk_conversations_llm
  foreign key
  (
    llm_id
  )
  references orac_core.llm_registry
  (
    llm_id
  )
;

alter table orac_core.conversations
  add constraint fk_conversations_user
  foreign key
  (
    user_id
  )
  references orac_core.users
  (
    user_id
  )
  on delete cascade
;

alter table orac_core.devices
  add constraint fk_devices_user
  foreign key
  (
    user_id
  )
  references orac_core.users
  (
    user_id
  )
  on delete cascade
;

alter table orac_core.messages
  add constraint fk_messages_conversation
  foreign key
  (
    conversation_id
  )
  references orac_core.conversations
  (
    conversation_id
  )
  on delete cascade
;

alter table orac_core.messages
  add constraint fk_messages_llm
  foreign key
  (
    llm_id
  )
  references orac_core.llm_registry
  (
    llm_id
  )
;

alter table orac_core.message_embeddings
  add constraint fk_msg_emb_message
  foreign key
  (
    message_id
  )
  references orac_core.messages
  (
    message_id
  )
  on delete cascade
;

alter table orac_core.user_preferences
  add constraint fk_user_preferences_user
  foreign key
  (
    user_id
  )
  references orac_core.users
  (
    user_id
  )
  on delete cascade
;

alter table orac_core.user_synonyms
  add constraint fk_user_synonyms_user
  foreign key
  (
    user_id
  )
  references orac_core.users
  (
    user_id
  )
  on delete cascade
;

alter table orac_core.user_prompt_elements
  add constraint fk_user_prompt_elements_user
  foreign key
  (
    user_id
  )
  references orac_core.users
  (
    user_id
  )
  on delete cascade
;
