"""Static checks for the retrieval cache/audit schema assets."""
# Author: Clive Bostock
# Date: 2026-05-26
# Description: Verifies retrieval tables and install-order wiring.

from __future__ import annotations

from pathlib import Path
import unittest


PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_ROOT = PROJECT_ROOT / "resources/db/schema"
CORE_ROOT = SCHEMA_ROOT / "orac_core"


class RetrievalSchemaTests(unittest.TestCase):
    """Static checks for the retrieval database asset set."""

    def _read(self, relative_path: str) -> str:
        path = PROJECT_ROOT / relative_path
        self.assertTrue(path.exists(), f"missing expected file: {relative_path}")
        return path.read_text(encoding="utf-8")

    def test_table_abbreviations_are_documented(self) -> None:
        abbreviations = self._read("docs/agent-guardrails/table-abbreviations.csv")

        self.assertIn("orac_core,orac_search_queries,orac_srch_q", abbreviations)
        self.assertIn("orac_core,orac_search_results,orac_srch_res", abbreviations)
        self.assertIn("orac_core,orac_fetched_sources,orac_fch_src", abbreviations)

    def test_retrieval_schema_assets_exist(self) -> None:
        expected_files = [
            "resources/db/schema/orac_core/table/orac_search_queries.sql",
            "resources/db/schema/orac_core/table/orac_search_results.sql",
            "resources/db/schema/orac_core/table/orac_fetched_sources.sql",
            "resources/db/schema/orac_core/index/orac_srch_q_pk.sql",
            "resources/db/schema/orac_core/index/orac_srch_res_pk.sql",
            "resources/db/schema/orac_core/index/orac_srch_res_srch_q_fk1_idx.sql",
            "resources/db/schema/orac_core/index/orac_fch_src_pk.sql",
            "resources/db/schema/orac_core/index/orac_fch_src_srch_res_fk1_idx.sql",
            "resources/db/schema/orac_core/constraint_pk/orac_srch_q_pk.sql",
            "resources/db/schema/orac_core/constraint_pk/orac_srch_res_pk.sql",
            "resources/db/schema/orac_core/constraint_pk/orac_fch_src_pk.sql",
            "resources/db/schema/orac_core/constraint_fk/orac_srch_res_orac_srch_q_fk1.sql",
            "resources/db/schema/orac_core/constraint_fk/orac_fch_src_srch_res_fk1.sql",
        ]

        for relative_path in expected_files:
            self.assertTrue(
                (PROJECT_ROOT / relative_path).exists(),
                f"missing expected file: {relative_path}",
            )

        query_sql = self._read("resources/db/schema/orac_core/table/orac_search_queries.sql")
        result_sql = self._read("resources/db/schema/orac_core/table/orac_search_results.sql")
        source_sql = self._read("resources/db/schema/orac_core/table/orac_fetched_sources.sql")
        self.assertIn("create table orac_core.orac_search_queries", query_sql)
        self.assertIn("create table orac_core.orac_search_results", result_sql)
        self.assertIn("create table orac_core.orac_fetched_sources", source_sql)
        self.assertIn("generated by default on null as identity", query_sql)
        self.assertIn("generated by default on null as identity", result_sql)
        self.assertIn("generated by default on null as identity", source_sql)

        result_fk = self._read("resources/db/schema/orac_core/constraint_fk/orac_srch_res_orac_srch_q_fk1.sql")
        source_fk = self._read("resources/db/schema/orac_core/constraint_fk/orac_fch_src_srch_res_fk1.sql")
        self.assertIn("foreign key", result_fk)
        self.assertIn("references orac_core.orac_search_queries", result_fk)
        self.assertIn("foreign key", source_fk)
        self.assertIn("references orac_core.orac_search_results", source_fk)

    def test_install_order_includes_retrieval_assets(self) -> None:
        run_all = self._read("resources/db/schema/orac_core/run_all.sql")

        self.assertIn("@table/orac_search_queries.sql", run_all)
        self.assertIn("@table/orac_search_results.sql", run_all)
        self.assertIn("@table/orac_fetched_sources.sql", run_all)
        self.assertIn("@index/orac_srch_q_pk.sql", run_all)
        self.assertIn("@index/orac_srch_res_pk.sql", run_all)
        self.assertIn("@index/orac_srch_res_srch_q_fk1_idx.sql", run_all)
        self.assertIn("@index/orac_fch_src_pk.sql", run_all)
        self.assertIn("@index/orac_fch_src_srch_res_fk1_idx.sql", run_all)
        self.assertIn("@constraint_pk/orac_srch_q_pk.sql", run_all)
        self.assertIn("@constraint_pk/orac_srch_res_pk.sql", run_all)
        self.assertIn("@constraint_pk/orac_fch_src_pk.sql", run_all)
        self.assertIn("@constraint_fk/orac_srch_res_orac_srch_q_fk1.sql", run_all)
        self.assertIn("@constraint_fk/orac_fch_src_srch_res_fk1.sql", run_all)

    def test_api_layer_exposes_retrieval_cache_tables(self) -> None:
        expected_views = (
            (
                "resources/db/schema/orac_api/view/orac_search_queries_v.sql",
                "create or replace force view orac_api.orac_search_queries_v",
                "from orac_core.orac_search_queries",
            ),
            (
                "resources/db/schema/orac_api/view/orac_search_results_v.sql",
                "create or replace force view orac_api.orac_search_results_v",
                "from orac_core.orac_search_results",
            ),
            (
                "resources/db/schema/orac_api/view/orac_fetched_sources_v.sql",
                "create or replace force view orac_api.orac_fetched_sources_v",
                "from orac_core.orac_fetched_sources",
            ),
        )

        for relative_path, create_view, source_table in expected_views:
            view_sql = self._read(relative_path).lower()
            with self.subTest(relative_path=relative_path):
                self.assertIn(create_view, view_sql)
                self.assertIn(source_table, view_sql)
                self.assertIn("row_version", view_sql)

        privileges = self._read(
            "resources/db/schema/orac_api/privilege/orac_api_core_table_access.sql"
        ).lower()
        for table_name in (
            "orac_search_queries",
            "orac_search_results",
            "orac_fetched_sources",
        ):
            self.assertIn(
                f"grant select, insert, update, delete on "
                f"orac_core.{table_name} to orac_api with grant option",
                privileges,
            )

    def test_retrieval_cache_has_no_downstream_grants_yet(self) -> None:
        downstream_grants = "\n".join(
            self._read(relative_path).lower()
            for relative_path in (
                "resources/db/schema/orac_api/grant/orac_tapi_consumer_access.sql",
                "resources/db/schema/orac_code/grant/orac_code_consumer_view_access.sql",
            )
        )

        for object_name in (
            "orac_search_queries",
            "orac_search_results",
            "orac_fetched_sources",
            "orac_search_queries_v",
            "orac_search_results_v",
            "orac_fetched_sources_v",
        ):
            self.assertNotIn(object_name, downstream_grants)
