# Author: Clive Bostock
# Date: 21-Jun-2026
# Description: SQLcl Liquibase defaults for on-demand core Orac database deltas.

changeLogFile=productController.xml
liquibase.command.contextFilter=core,prod
liquibase.command.labelFilter=core
searchPath=/home/oracle/orac/schema
logLevel=info
