--liquibase formatted sql

--changeset clive:conversations_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.conversations_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   conversations_tapi
-- Source file name :   conversations_tapi.sql
-- Purpose          :   Table API (TAPI) for table conversations
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                  in out   orac_api.conversations_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.session_id', p_row.session_id);
      logger_user.logger.append_param(l_params, '  p_row.llm_id', p_row.llm_id);
      logger_user.logger.append_param(l_params, '  p_row.title', p_row.title);
      logger_user.logger.append_param(l_params, '  p_row.state', p_row.state);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.conversations_v
         (
              user_id
            , session_id
            , llm_id
            , title
            , state
         )
      values
         (
              p_row.user_id
            , p_row.session_id
            , p_row.llm_id
            , p_row.title
            , p_row.state
         )
      returning
              conversation_id
            , row_version
            into
              p_row.conversation_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id              in       orac_api.conversations_v.user_id%type
      , p_session_id           in       orac_api.conversations_v.session_id%type
      , p_llm_id               in       orac_api.conversations_v.llm_id%type
      , p_title                in       orac_api.conversations_v.title%type                                     := 'Brief exchange...'
      , p_state                in       orac_api.conversations_v.state%type                                     := 'open'
      , p_row_version             out   orac_api.conversations_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_session_id', p_session_id);
      logger_user.logger.append_param(l_params, '  p_llm_id', p_llm_id);
      logger_user.logger.append_param(l_params, '  p_title', p_title);
      logger_user.logger.append_param(l_params, '  p_state', p_state);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.conversations_v
         (
              user_id
            , session_id
            , llm_id
            , title
            , state
         )
      values
         (
              p_user_id
            , p_session_id
            , p_llm_id
            , p_title
            , p_state
         )
      returning
              conversation_id
            , row_version
            into
              p_conversation_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure get
   (
        p_conversation_id      in       orac_api.conversations_v.conversation_id%type
      , p_row                     out   orac_api.conversations_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_conversation_id', p_conversation_id);

      logger.log('START', l_scope, null, l_params);

      select
           conversation_id
         , user_id
         , session_id
         , llm_id
         , title
         , state
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.conversation_id
         , p_row.user_id
         , p_row.session_id
         , p_row.llm_id
         , p_row.title
         , p_row.state
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.conversations_v
      where
            conversation_id = p_conversation_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure get
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id                 out   orac_api.conversations_v.user_id%type
      , p_session_id              out   orac_api.conversations_v.session_id%type
      , p_llm_id                  out   orac_api.conversations_v.llm_id%type
      , p_title                   out   orac_api.conversations_v.title%type
      , p_state                   out   orac_api.conversations_v.state%type
      , p_created_on              out   orac_api.conversations_v.created_on%type
      , p_created_by              out   orac_api.conversations_v.created_by%type
      , p_updated_on              out   orac_api.conversations_v.updated_on%type
      , p_updated_by              out   orac_api.conversations_v.updated_by%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_conversation_id', p_conversation_id);

      logger.log('START', l_scope, null, l_params);

      select
           conversation_id
         , user_id
         , session_id
         , llm_id
         , title
         , state
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_conversation_id
         , p_user_id
         , p_session_id
         , p_llm_id
         , p_title
         , p_state
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.conversations_v
      where
            conversation_id = p_conversation_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_conversation_id      in       orac_api.conversations_v.conversation_id%type
      , p_row                  in out   orac_api.conversations_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_conversation_id', p_conversation_id);
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.session_id', p_row.session_id);
      logger_user.logger.append_param(l_params, '  p_row.llm_id', p_row.llm_id);
      logger_user.logger.append_param(l_params, '  p_row.title', p_row.title);
      logger_user.logger.append_param(l_params, '  p_row.state', p_row.state);

      logger.log('START', l_scope, null, l_params);

      update orac_api.conversations_v
      set
           user_id                        = p_row.user_id
         , session_id                     = p_row.session_id
         , llm_id                         = p_row.llm_id
         , title                          = p_row.title
         , state                          = p_row.state
      where
            conversation_id = p_conversation_id
      returning
              conversation_id
            , row_version
            into
              p_row.conversation_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id              in       orac_api.conversations_v.user_id%type
      , p_session_id           in       orac_api.conversations_v.session_id%type
      , p_llm_id               in       orac_api.conversations_v.llm_id%type
      , p_title                in       orac_api.conversations_v.title%type
      , p_state                in       orac_api.conversations_v.state%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_conversation_id', p_conversation_id);
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_session_id', p_session_id);
      logger_user.logger.append_param(l_params, '  p_llm_id', p_llm_id);
      logger_user.logger.append_param(l_params, '  p_title', p_title);
      logger_user.logger.append_param(l_params, '  p_state', p_state);

      logger.log('START', l_scope, null, l_params);

      update orac_api.conversations_v
      set
           user_id                        = p_user_id
         , session_id                     = p_session_id
         , llm_id                         = p_llm_id
         , title                          = p_title
         , state                          = p_state
      where
            conversation_id = p_conversation_id
      returning
              conversation_id
            , row_version
            into
              p_conversation_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure del
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'del';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_conversation_id', p_conversation_id);

      logger.log('START', l_scope, null, l_params);

        delete
          from orac_api.conversations_v
         where
               conversation_id = p_conversation_id
      returning
              conversation_id
            , row_version
            into
              p_conversation_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end del;

end conversations_tapi;
/
--rollback drop package orac_api.conversations_tapi
