--liquibase formatted sql

--changeset clive:devices_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.devices_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   devices_tapi
-- Source file name :   devices_tapi.sql
-- Purpose          :   Table API (TAPI) for table devices
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row              in out   orac_api.devices_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.host_name', p_row.host_name);
      logger_user.logger.append_param(l_params, '  p_row.is_active', p_row.is_active);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.devices_v
         (
              device_id
            , user_id
            , host_name
            , is_active
         )
      values
         (
              p_device_id
            , p_row.user_id
            , p_row.host_name
            , p_row.is_active
         )
      returning
              device_id
            , row_version
            into
              p_row.device_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id          in       orac_api.devices_v.user_id%type
      , p_host_name        in       orac_api.devices_v.host_name%type
      , p_is_active        in       orac_api.devices_v.is_active%type                                           := 'Y'
      , p_row_version         out   orac_api.devices_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_host_name', p_host_name);
      logger_user.logger.append_param(l_params, '  p_is_active', p_is_active);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.devices_v
         (
              device_id
            , user_id
            , host_name
            , is_active
         )
      values
         (
              p_device_id
            , p_user_id
            , p_host_name
            , p_is_active
         )
      returning
              device_id
            , row_version
            into
              p_device_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure get
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row                 out   orac_api.devices_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);

      logger.log('START', l_scope, null, l_params);

      select
           device_id
         , user_id
         , host_name
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.device_id
         , p_row.user_id
         , p_row.host_name
         , p_row.is_active
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.devices_v
      where
            device_id = p_device_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure get
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id             out   orac_api.devices_v.user_id%type
      , p_host_name           out   orac_api.devices_v.host_name%type
      , p_is_active           out   orac_api.devices_v.is_active%type
      , p_created_on          out   orac_api.devices_v.created_on%type
      , p_created_by          out   orac_api.devices_v.created_by%type
      , p_updated_on          out   orac_api.devices_v.updated_on%type
      , p_updated_by          out   orac_api.devices_v.updated_by%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);

      logger.log('START', l_scope, null, l_params);

      select
           device_id
         , user_id
         , host_name
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_device_id
         , p_user_id
         , p_host_name
         , p_is_active
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.devices_v
      where
            device_id = p_device_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row              in out   orac_api.devices_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.host_name', p_row.host_name);
      logger_user.logger.append_param(l_params, '  p_row.is_active', p_row.is_active);

      logger.log('START', l_scope, null, l_params);

      update orac_api.devices_v
      set
           user_id                        = p_row.user_id
         , host_name                      = p_row.host_name
         , is_active                      = p_row.is_active
      where
            device_id = p_device_id
      returning
              device_id
            , row_version
            into
              p_row.device_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id          in       orac_api.devices_v.user_id%type
      , p_host_name        in       orac_api.devices_v.host_name%type
      , p_is_active        in       orac_api.devices_v.is_active%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_host_name', p_host_name);
      logger_user.logger.append_param(l_params, '  p_is_active', p_is_active);

      logger.log('START', l_scope, null, l_params);

      update orac_api.devices_v
      set
           user_id                        = p_user_id
         , host_name                      = p_host_name
         , is_active                      = p_is_active
      where
            device_id = p_device_id
      returning
              device_id
            , row_version
            into
              p_device_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure del
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'del';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_device_id', p_device_id);

      logger.log('START', l_scope, null, l_params);

        delete
          from orac_api.devices_v
         where
               device_id = p_device_id
      returning
              device_id
            , row_version
            into
              p_device_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end del;

end devices_tapi;
/
--rollback drop package orac_api.devices_tapi
