--liquibase formatted sql

--changeset clive:llm_registry_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.llm_registry_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   llm_registry_tapi
-- Source file name :   llm_registry_tapi.sql
-- Purpose          :   Table API (TAPI) for table llm_registry
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                     in out   orac_api.llm_registry_v%rowtype
   )
   is
   begin

      insert into orac_api.llm_registry_v
         (
              name
            , provider
            , model
            , context_policy
            , max_context_tokens
            , is_enabled
            , properties
         )
      values
         (
              p_row.name
            , p_row.provider
            , p_row.model
            , p_row.context_policy
            , p_row.max_context_tokens
            , p_row.is_enabled
            , p_row.properties
         )
      returning
              llm_id
            , row_version
            into
              p_row.llm_id
            , p_row.row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_name                    in       orac_api.llm_registry_v.name%type
      , p_provider                in       orac_api.llm_registry_v.provider%type
      , p_model                   in       orac_api.llm_registry_v.model%type
      , p_context_policy          in       orac_api.llm_registry_v.context_policy%type
      , p_max_context_tokens      in       orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled              in       orac_api.llm_registry_v.is_enabled%type                              := 'Y'
      , p_properties              in       orac_api.llm_registry_v.properties%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   )
   is
   begin

      insert into orac_api.llm_registry_v
         (
              name
            , provider
            , model
            , context_policy
            , max_context_tokens
            , is_enabled
            , properties
         )
      values
         (
              p_name
            , p_provider
            , p_model
            , p_context_policy
            , p_max_context_tokens
            , p_is_enabled
            , p_properties
         )
      returning
              llm_id
            , row_version
            into
              g_row.llm_id
            , p_row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure get
   (
        p_llm_id                  in       orac_api.llm_registry_v.llm_id%type
      , p_row                        out   orac_api.llm_registry_v%rowtype
   )
   is
   begin

      select
           llm_id
         , name
         , provider
         , model
         , context_policy
         , max_context_tokens
         , is_enabled
         , properties
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.llm_id
         , p_row.name
         , p_row.provider
         , p_row.model
         , p_row.context_policy
         , p_row.max_context_tokens
         , p_row.is_enabled
         , p_row.properties
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.llm_registry_v
      where
            llm_id = p_llm_id;
   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure get
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_name                       out   orac_api.llm_registry_v.name%type
      , p_provider                   out   orac_api.llm_registry_v.provider%type
      , p_model                      out   orac_api.llm_registry_v.model%type
      , p_context_policy             out   orac_api.llm_registry_v.context_policy%type
      , p_max_context_tokens         out   orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled                 out   orac_api.llm_registry_v.is_enabled%type
      , p_properties                 out   orac_api.llm_registry_v.properties%type
      , p_created_on                 out   orac_api.llm_registry_v.created_on%type
      , p_created_by                 out   orac_api.llm_registry_v.created_by%type
      , p_updated_on                 out   orac_api.llm_registry_v.updated_on%type
      , p_updated_by                 out   orac_api.llm_registry_v.updated_by%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   )
   is
   begin

      select
           llm_id
         , name
         , provider
         , model
         , context_policy
         , max_context_tokens
         , is_enabled
         , properties
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_llm_id
         , p_name
         , p_provider
         , p_model
         , p_context_policy
         , p_max_context_tokens
         , p_is_enabled
         , p_properties
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.llm_registry_v
      where
            llm_id = p_llm_id;
   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_llm_id                  in       orac_api.llm_registry_v.llm_id%type
      , p_row                     in out   orac_api.llm_registry_v%rowtype
   )
   is
   begin

      update orac_api.llm_registry_v
      set
           name                           = p_row.name
         , provider                       = p_row.provider
         , model                          = p_row.model
         , context_policy                 = p_row.context_policy
         , max_context_tokens             = p_row.max_context_tokens
         , is_enabled                     = p_row.is_enabled
         , properties                     = p_row.properties
      where
            llm_id = p_llm_id
      returning
              llm_id
            , row_version
            into
              p_row.llm_id
            , p_row.row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_name                    in       orac_api.llm_registry_v.name%type
      , p_provider                in       orac_api.llm_registry_v.provider%type
      , p_model                   in       orac_api.llm_registry_v.model%type
      , p_context_policy          in       orac_api.llm_registry_v.context_policy%type
      , p_max_context_tokens      in       orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled              in       orac_api.llm_registry_v.is_enabled%type
      , p_properties              in       orac_api.llm_registry_v.properties%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   )
   is
   begin

      update orac_api.llm_registry_v
      set
           name                           = p_name
         , provider                       = p_provider
         , model                          = p_model
         , context_policy                 = p_context_policy
         , max_context_tokens             = p_max_context_tokens
         , is_enabled                     = p_is_enabled
         , properties                     = p_properties
      where
            llm_id = p_llm_id
      returning
              llm_id
            , row_version
            into
              p_llm_id
            , p_row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure del
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   )
   is
   begin

        delete
          from orac_api.llm_registry_v
         where
               llm_id = p_llm_id
      returning
              llm_id
            , row_version
            into
              p_llm_id
            , p_row_version;
   end del;

end llm_registry_tapi;
/
--rollback drop package orac_api.llm_registry_tapi
