--liquibase formatted sql

--changeset clive:messages_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.messages_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   messages_tapi
-- Source file name :   messages_tapi.sql
-- Purpose          :   Table API (TAPI) for table messages
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                  in out   orac_api.messages_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_row.conversation_id', p_row.conversation_id);
      logger_user.logger.append_param(l_params, '  p_row.message_type', p_row.message_type);
      logger_user.logger.append_param(l_params, '  p_row.turn_index', p_row.turn_index);
      logger_user.logger.append_param(l_params, '  p_row.role', p_row.role);
      logger_user.logger.append_param(l_params, '  p_row.content', p_row.content);
      logger_user.logger.append_param(l_params, '  p_row.tokens_used', p_row.tokens_used);
      logger_user.logger.append_param(l_params, '  p_row.meta', p_row.meta);
      logger_user.logger.append_param(l_params, '  p_row.llm_id', p_row.llm_id);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.messages_v
         (
              conversation_id
            , message_type
            , turn_index
            , role
            , content
            , tokens_used
            , meta
            , llm_id
         )
      values
         (
              p_row.conversation_id
            , p_row.message_type
            , p_row.turn_index
            , p_row.role
            , p_row.content
            , p_row.tokens_used
            , p_row.meta
            , p_row.llm_id
         )
      returning
              message_id
            , row_version
            into
              p_row.message_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id      in       orac_api.messages_v.conversation_id%type
      , p_message_type         in       orac_api.messages_v.message_type%type
      , p_turn_index           in       orac_api.messages_v.turn_index%type
      , p_role                 in       orac_api.messages_v.role%type
      , p_content              in       orac_api.messages_v.content%type
      , p_tokens_used          in       orac_api.messages_v.tokens_used%type
      , p_meta                 in       orac_api.messages_v.meta%type
      , p_llm_id               in       orac_api.messages_v.llm_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_conversation_id', p_conversation_id);
      logger_user.logger.append_param(l_params, '  p_message_type', p_message_type);
      logger_user.logger.append_param(l_params, '  p_turn_index', p_turn_index);
      logger_user.logger.append_param(l_params, '  p_role', p_role);
      logger_user.logger.append_param(l_params, '  p_content', p_content);
      logger_user.logger.append_param(l_params, '  p_tokens_used', p_tokens_used);
      logger_user.logger.append_param(l_params, '  p_meta', p_meta);
      logger_user.logger.append_param(l_params, '  p_llm_id', p_llm_id);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.messages_v
         (
              conversation_id
            , message_type
            , turn_index
            , role
            , content
            , tokens_used
            , meta
            , llm_id
         )
      values
         (
              p_conversation_id
            , p_message_type
            , p_turn_index
            , p_role
            , p_content
            , p_tokens_used
            , p_meta
            , p_llm_id
         )
      returning
              message_id
            , row_version
            into
              p_message_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure get
   (
        p_message_id           in       orac_api.messages_v.message_id%type
      , p_row                     out   orac_api.messages_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_message_id', p_message_id);

      logger.log('START', l_scope, null, l_params);

      select
           message_id
         , conversation_id
         , message_type
         , turn_index
         , role
         , content
         , tokens_used
         , meta
         , llm_id
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.message_id
         , p_row.conversation_id
         , p_row.message_type
         , p_row.turn_index
         , p_row.role
         , p_row.content
         , p_row.tokens_used
         , p_row.meta
         , p_row.llm_id
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.messages_v
      where
            message_id = p_message_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure get
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id         out   orac_api.messages_v.conversation_id%type
      , p_message_type            out   orac_api.messages_v.message_type%type
      , p_turn_index              out   orac_api.messages_v.turn_index%type
      , p_role                    out   orac_api.messages_v.role%type
      , p_content                 out   orac_api.messages_v.content%type
      , p_tokens_used             out   orac_api.messages_v.tokens_used%type
      , p_meta                    out   orac_api.messages_v.meta%type
      , p_llm_id                  out   orac_api.messages_v.llm_id%type
      , p_created_on              out   orac_api.messages_v.created_on%type
      , p_created_by              out   orac_api.messages_v.created_by%type
      , p_updated_on              out   orac_api.messages_v.updated_on%type
      , p_updated_by              out   orac_api.messages_v.updated_by%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_message_id', p_message_id);

      logger.log('START', l_scope, null, l_params);

      select
           message_id
         , conversation_id
         , message_type
         , turn_index
         , role
         , content
         , tokens_used
         , meta
         , llm_id
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_message_id
         , p_conversation_id
         , p_message_type
         , p_turn_index
         , p_role
         , p_content
         , p_tokens_used
         , p_meta
         , p_llm_id
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.messages_v
      where
            message_id = p_message_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_message_id           in       orac_api.messages_v.message_id%type
      , p_row                  in out   orac_api.messages_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_message_id', p_message_id);
      logger_user.logger.append_param(l_params, '  p_row.conversation_id', p_row.conversation_id);
      logger_user.logger.append_param(l_params, '  p_row.message_type', p_row.message_type);
      logger_user.logger.append_param(l_params, '  p_row.turn_index', p_row.turn_index);
      logger_user.logger.append_param(l_params, '  p_row.role', p_row.role);
      logger_user.logger.append_param(l_params, '  p_row.content', p_row.content);
      logger_user.logger.append_param(l_params, '  p_row.tokens_used', p_row.tokens_used);
      logger_user.logger.append_param(l_params, '  p_row.meta', p_row.meta);
      logger_user.logger.append_param(l_params, '  p_row.llm_id', p_row.llm_id);

      logger.log('START', l_scope, null, l_params);

      update orac_api.messages_v
      set
           conversation_id                = p_row.conversation_id
         , message_type                   = p_row.message_type
         , turn_index                     = p_row.turn_index
         , role                           = p_row.role
         , content                        = p_row.content
         , tokens_used                    = p_row.tokens_used
         , meta                           = p_row.meta
         , llm_id                         = p_row.llm_id
      where
            message_id = p_message_id
      returning
              message_id
            , row_version
            into
              p_row.message_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id      in       orac_api.messages_v.conversation_id%type
      , p_message_type         in       orac_api.messages_v.message_type%type
      , p_turn_index           in       orac_api.messages_v.turn_index%type
      , p_role                 in       orac_api.messages_v.role%type
      , p_content              in       orac_api.messages_v.content%type
      , p_tokens_used          in       orac_api.messages_v.tokens_used%type
      , p_meta                 in       orac_api.messages_v.meta%type
      , p_llm_id               in       orac_api.messages_v.llm_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_message_id', p_message_id);
      logger_user.logger.append_param(l_params, '  p_conversation_id', p_conversation_id);
      logger_user.logger.append_param(l_params, '  p_message_type', p_message_type);
      logger_user.logger.append_param(l_params, '  p_turn_index', p_turn_index);
      logger_user.logger.append_param(l_params, '  p_role', p_role);
      logger_user.logger.append_param(l_params, '  p_content', p_content);
      logger_user.logger.append_param(l_params, '  p_tokens_used', p_tokens_used);
      logger_user.logger.append_param(l_params, '  p_meta', p_meta);
      logger_user.logger.append_param(l_params, '  p_llm_id', p_llm_id);

      logger.log('START', l_scope, null, l_params);

      update orac_api.messages_v
      set
           conversation_id                = p_conversation_id
         , message_type                   = p_message_type
         , turn_index                     = p_turn_index
         , role                           = p_role
         , content                        = p_content
         , tokens_used                    = p_tokens_used
         , meta                           = p_meta
         , llm_id                         = p_llm_id
      where
            message_id = p_message_id
      returning
              message_id
            , row_version
            into
              p_message_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure del
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'del';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_message_id', p_message_id);

      logger.log('START', l_scope, null, l_params);

        delete
          from orac_api.messages_v
         where
               message_id = p_message_id
      returning
              message_id
            , row_version
            into
              p_message_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end del;

end messages_tapi;
/
--rollback drop package orac_api.messages_tapi
