--liquibase formatted sql

--changeset clive:message_embeddings_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package body orac_api.message_embeddings_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   message_embeddings_tapi
-- Source file name :   message_embeddings_tapi.sql
-- Purpose          :   Table API (TAPI) for table message_embeddings
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                     in out   orac_api.message_embeddings_v%rowtype
   )
   is
   begin

      insert into orac_api.message_embeddings_v
         (
              message_id
            , chunk_index
            , span_start
            , span_end
            , lossless_text
            , content_snapshot
            , embedding
            , embedding_model
            , embedding_provider
            , distance_metric
            , tokens_used
         )
      values
         (
              p_row.message_id
            , p_row.chunk_index
            , p_row.span_start
            , p_row.span_end
            , p_row.lossless_text
            , p_row.content_snapshot
            , p_row.embedding
            , p_row.embedding_model
            , p_row.embedding_provider
            , p_row.distance_metric
            , p_row.tokens_used
         )
      returning
              emb_id
            , row_version
            into
              p_row.emb_id
            , p_row.row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id              in       orac_api.message_embeddings_v.message_id%type
      , p_chunk_index             in       orac_api.message_embeddings_v.chunk_index%type                       := 1
      , p_span_start              in       orac_api.message_embeddings_v.span_start%type
      , p_span_end                in       orac_api.message_embeddings_v.span_end%type
      , p_lossless_text           in       orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot        in       orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding               in       orac_api.message_embeddings_v.embedding%type
      , p_embedding_model         in       orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider      in       orac_api.message_embeddings_v.embedding_provider%type                := 'oracle'
      , p_distance_metric         in       orac_api.message_embeddings_v.distance_metric%type                   := 'COSINE'
      , p_tokens_used             in       orac_api.message_embeddings_v.tokens_used%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   )
   is
   begin

      insert into orac_api.message_embeddings_v
         (
              message_id
            , chunk_index
            , span_start
            , span_end
            , lossless_text
            , content_snapshot
            , embedding
            , embedding_model
            , embedding_provider
            , distance_metric
            , tokens_used
         )
      values
         (
              p_message_id
            , p_chunk_index
            , p_span_start
            , p_span_end
            , p_lossless_text
            , p_content_snapshot
            , p_embedding
            , p_embedding_model
            , p_embedding_provider
            , p_distance_metric
            , p_tokens_used
         )
      returning
              emb_id
            , row_version
            into
              p_emb_id
            , p_row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure get
   (
        p_emb_id                  in       orac_api.message_embeddings_v.emb_id%type
      , p_row                        out   orac_api.message_embeddings_v%rowtype
   )
   is
   begin

      select
           emb_id
         , message_id
         , chunk_index
         , span_start
         , span_end
         , lossless_text
         , content_snapshot
         , embedding
         , embedding_model
         , embedding_provider
         , distance_metric
         , tokens_used
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.emb_id
         , p_row.message_id
         , p_row.chunk_index
         , p_row.span_start
         , p_row.span_end
         , p_row.lossless_text
         , p_row.content_snapshot
         , p_row.embedding
         , p_row.embedding_model
         , p_row.embedding_provider
         , p_row.distance_metric
         , p_row.tokens_used
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.message_embeddings_v
      where
            emb_id = p_emb_id;
   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure get
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id                 out   orac_api.message_embeddings_v.message_id%type
      , p_chunk_index                out   orac_api.message_embeddings_v.chunk_index%type
      , p_span_start                 out   orac_api.message_embeddings_v.span_start%type
      , p_span_end                   out   orac_api.message_embeddings_v.span_end%type
      , p_lossless_text              out   orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot           out   orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding                  out   orac_api.message_embeddings_v.embedding%type
      , p_embedding_model            out   orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider         out   orac_api.message_embeddings_v.embedding_provider%type
      , p_distance_metric            out   orac_api.message_embeddings_v.distance_metric%type
      , p_tokens_used                out   orac_api.message_embeddings_v.tokens_used%type
      , p_created_on                 out   orac_api.message_embeddings_v.created_on%type
      , p_created_by                 out   orac_api.message_embeddings_v.created_by%type
      , p_updated_on                 out   orac_api.message_embeddings_v.updated_on%type
      , p_updated_by                 out   orac_api.message_embeddings_v.updated_by%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   )
   is
   begin

      select
           emb_id
         , message_id
         , chunk_index
         , span_start
         , span_end
         , lossless_text
         , content_snapshot
         , embedding
         , embedding_model
         , embedding_provider
         , distance_metric
         , tokens_used
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_emb_id
         , p_message_id
         , p_chunk_index
         , p_span_start
         , p_span_end
         , p_lossless_text
         , p_content_snapshot
         , p_embedding
         , p_embedding_model
         , p_embedding_provider
         , p_distance_metric
         , p_tokens_used
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.message_embeddings_v
      where
            emb_id = p_emb_id;
   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_emb_id                  in       orac_api.message_embeddings_v.emb_id%type
      , p_row                     in out   orac_api.message_embeddings_v%rowtype
   )
   is
   begin

      update orac_api.message_embeddings_v
      set
           message_id                     = p_row.message_id
         , chunk_index                    = p_row.chunk_index
         , span_start                     = p_row.span_start
         , span_end                       = p_row.span_end
         , lossless_text                  = p_row.lossless_text
         , content_snapshot               = p_row.content_snapshot
         , embedding                      = p_row.embedding
         , embedding_model                = p_row.embedding_model
         , embedding_provider             = p_row.embedding_provider
         , distance_metric                = p_row.distance_metric
         , tokens_used                    = p_row.tokens_used
      where
            emb_id = p_emb_id
      returning
              emb_id
            , row_version
            into
              p_row.emb_id
            , p_row.row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id              in       orac_api.message_embeddings_v.message_id%type
      , p_chunk_index             in       orac_api.message_embeddings_v.chunk_index%type
      , p_span_start              in       orac_api.message_embeddings_v.span_start%type
      , p_span_end                in       orac_api.message_embeddings_v.span_end%type
      , p_lossless_text           in       orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot        in       orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding               in       orac_api.message_embeddings_v.embedding%type
      , p_embedding_model         in       orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider      in       orac_api.message_embeddings_v.embedding_provider%type
      , p_distance_metric         in       orac_api.message_embeddings_v.distance_metric%type
      , p_tokens_used             in       orac_api.message_embeddings_v.tokens_used%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   )
   is
   begin

      update orac_api.message_embeddings_v
      set
           message_id                     = p_message_id
         , chunk_index                    = p_chunk_index
         , span_start                     = p_span_start
         , span_end                       = p_span_end
         , lossless_text                  = p_lossless_text
         , content_snapshot               = p_content_snapshot
         , embedding                      = p_embedding
         , embedding_model                = p_embedding_model
         , embedding_provider             = p_embedding_provider
         , distance_metric                = p_distance_metric
         , tokens_used                    = p_tokens_used
      where
            emb_id = p_emb_id
      returning
              emb_id
            , row_version
            into
              p_emb_id
            , p_row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure del
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   )
   is
   begin

        delete
          from orac_api.message_embeddings_v
         where
               emb_id = p_emb_id
      returning
              emb_id
            , row_version
            into
              p_emb_id
            , p_row_version;
   end del;

end message_embeddings_tapi;
/
--rollback drop package body orac_api.message_embeddings_tapi;