--liquibase formatted sql

--changeset clive:orac_personalities_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.orac_personalities_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   orac_personalities_tapi
-- Source file name :   orac_personalities_tapi.sql
-- Purpose          :   Table API (TAPI) for table orac_personalities
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                      in out   orac_api.orac_personalities_v%rowtype
   )
   is
   begin

      insert into orac_api.orac_personalities_v
         (
              personality_code
            , personality_name
            , description
            , attitude_base_level
            , sarcasm_level
            , verbosity_level
            , allow_humour
            , allow_critique
            , enforce_precision
            , admit_uncertainty
            , packaged_persona
            , system_prompt
            , style_prompt
            , is_active
         )
      values
         (
              p_row.personality_code
            , p_row.personality_name
            , p_row.description
            , p_row.attitude_base_level
            , p_row.sarcasm_level
            , p_row.verbosity_level
            , p_row.allow_humour
            , p_row.allow_critique
            , p_row.enforce_precision
            , p_row.admit_uncertainty
            , p_row.packaged_persona
            , p_row.system_prompt
            , p_row.style_prompt
            , p_row.is_active
         )
      returning
              personality_id
            , row_version
            into
              p_row.personality_id
            , p_row.row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_personality_code         in       orac_api.orac_personalities_v.personality_code%type
      , p_personality_name         in       orac_api.orac_personalities_v.personality_name%type
      , p_description              in       orac_api.orac_personalities_v.description%type
      , p_attitude_base_level      in       orac_api.orac_personalities_v.attitude_base_level%type              := 1
      , p_sarcasm_level            in       orac_api.orac_personalities_v.sarcasm_level%type                    := 1
      , p_verbosity_level          in       orac_api.orac_personalities_v.verbosity_level%type                  := 1
      , p_allow_humour             in       orac_api.orac_personalities_v.allow_humour%type                     := true
      , p_allow_critique           in       orac_api.orac_personalities_v.allow_critique%type                   := true
      , p_enforce_precision        in       orac_api.orac_personalities_v.enforce_precision%type                := true
      , p_admit_uncertainty        in       orac_api.orac_personalities_v.admit_uncertainty%type                := true
      , p_packaged_persona         in       orac_api.orac_personalities_v.packaged_persona%type                 := false
      , p_system_prompt            in       orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt             in       orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                in       orac_api.orac_personalities_v.is_active%type                        := true
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   )
   is
   begin

      insert into orac_api.orac_personalities_v
         (
              personality_code
            , personality_name
            , description
            , attitude_base_level
            , sarcasm_level
            , verbosity_level
            , allow_humour
            , allow_critique
            , enforce_precision
            , admit_uncertainty
            , packaged_persona
            , system_prompt
            , style_prompt
            , is_active
         )
      values
         (
              p_personality_code
            , p_personality_name
            , p_description
            , p_attitude_base_level
            , p_sarcasm_level
            , p_verbosity_level
            , p_allow_humour
            , p_allow_critique
            , p_enforce_precision
            , p_admit_uncertainty
            , p_packaged_persona
            , p_system_prompt
            , p_style_prompt
            , p_is_active
         )
      returning
              personality_id
            , row_version
            into
              g_row.personality_id
            , p_row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure get
   (
        p_personality_id           in       orac_api.orac_personalities_v.personality_id%type
      , p_row                         out   orac_api.orac_personalities_v%rowtype
   )
   is
   begin

      select
           personality_id
         , personality_code
         , personality_name
         , description
         , attitude_base_level
         , sarcasm_level
         , verbosity_level
         , allow_humour
         , allow_critique
         , enforce_precision
         , admit_uncertainty
         , packaged_persona
         , system_prompt
         , style_prompt
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.personality_id
         , p_row.personality_code
         , p_row.personality_name
         , p_row.description
         , p_row.attitude_base_level
         , p_row.sarcasm_level
         , p_row.verbosity_level
         , p_row.allow_humour
         , p_row.allow_critique
         , p_row.enforce_precision
         , p_row.admit_uncertainty
         , p_row.packaged_persona
         , p_row.system_prompt
         , p_row.style_prompt
         , p_row.is_active
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.orac_personalities_v
      where
            personality_id = p_personality_id;
   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure get
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_personality_code            out   orac_api.orac_personalities_v.personality_code%type
      , p_personality_name            out   orac_api.orac_personalities_v.personality_name%type
      , p_description                 out   orac_api.orac_personalities_v.description%type
      , p_attitude_base_level         out   orac_api.orac_personalities_v.attitude_base_level%type
      , p_sarcasm_level               out   orac_api.orac_personalities_v.sarcasm_level%type
      , p_verbosity_level             out   orac_api.orac_personalities_v.verbosity_level%type
      , p_allow_humour                out   orac_api.orac_personalities_v.allow_humour%type
      , p_allow_critique              out   orac_api.orac_personalities_v.allow_critique%type
      , p_enforce_precision           out   orac_api.orac_personalities_v.enforce_precision%type
      , p_admit_uncertainty           out   orac_api.orac_personalities_v.admit_uncertainty%type
      , p_packaged_persona            out   orac_api.orac_personalities_v.packaged_persona%type
      , p_system_prompt               out   orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt                out   orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                   out   orac_api.orac_personalities_v.is_active%type
      , p_created_on                  out   orac_api.orac_personalities_v.created_on%type
      , p_created_by                  out   orac_api.orac_personalities_v.created_by%type
      , p_updated_on                  out   orac_api.orac_personalities_v.updated_on%type
      , p_updated_by                  out   orac_api.orac_personalities_v.updated_by%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   )
   is
   begin

      select
           personality_id
         , personality_code
         , personality_name
         , description
         , attitude_base_level
         , sarcasm_level
         , verbosity_level
         , allow_humour
         , allow_critique
         , enforce_precision
         , admit_uncertainty
         , packaged_persona
         , system_prompt
         , style_prompt
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_personality_id
         , p_personality_code
         , p_personality_name
         , p_description
         , p_attitude_base_level
         , p_sarcasm_level
         , p_verbosity_level
         , p_allow_humour
         , p_allow_critique
         , p_enforce_precision
         , p_admit_uncertainty
         , p_packaged_persona
         , p_system_prompt
         , p_style_prompt
         , p_is_active
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.orac_personalities_v
      where
            personality_id = p_personality_id;
   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_personality_id           in       orac_api.orac_personalities_v.personality_id%type
      , p_row                      in out   orac_api.orac_personalities_v%rowtype
   )
   is
   begin

      update orac_api.orac_personalities_v
      set
           personality_code               = p_row.personality_code
         , personality_name               = p_row.personality_name
         , description                    = p_row.description
         , attitude_base_level            = p_row.attitude_base_level
         , sarcasm_level                  = p_row.sarcasm_level
         , verbosity_level                = p_row.verbosity_level
         , allow_humour                   = p_row.allow_humour
         , allow_critique                 = p_row.allow_critique
         , enforce_precision              = p_row.enforce_precision
         , admit_uncertainty              = p_row.admit_uncertainty
         , packaged_persona               = p_row.packaged_persona
         , system_prompt                  = p_row.system_prompt
         , style_prompt                   = p_row.style_prompt
         , is_active                      = p_row.is_active
      where
            personality_id = p_personality_id
      returning
              personality_id
            , row_version
            into
              p_row.personality_id
            , p_row.row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_personality_code         in       orac_api.orac_personalities_v.personality_code%type
      , p_personality_name         in       orac_api.orac_personalities_v.personality_name%type
      , p_description              in       orac_api.orac_personalities_v.description%type
      , p_attitude_base_level      in       orac_api.orac_personalities_v.attitude_base_level%type
      , p_sarcasm_level            in       orac_api.orac_personalities_v.sarcasm_level%type
      , p_verbosity_level          in       orac_api.orac_personalities_v.verbosity_level%type
      , p_allow_humour             in       orac_api.orac_personalities_v.allow_humour%type
      , p_allow_critique           in       orac_api.orac_personalities_v.allow_critique%type
      , p_enforce_precision        in       orac_api.orac_personalities_v.enforce_precision%type
      , p_admit_uncertainty        in       orac_api.orac_personalities_v.admit_uncertainty%type
      , p_packaged_persona         in       orac_api.orac_personalities_v.packaged_persona%type
      , p_system_prompt            in       orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt             in       orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                in       orac_api.orac_personalities_v.is_active%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   )
   is
   begin

      update orac_api.orac_personalities_v
      set
           personality_code               = p_personality_code
         , personality_name               = p_personality_name
         , description                    = p_description
         , attitude_base_level            = p_attitude_base_level
         , sarcasm_level                  = p_sarcasm_level
         , verbosity_level                = p_verbosity_level
         , allow_humour                   = p_allow_humour
         , allow_critique                 = p_allow_critique
         , enforce_precision              = p_enforce_precision
         , admit_uncertainty              = p_admit_uncertainty
         , packaged_persona               = p_packaged_persona
         , system_prompt                  = p_system_prompt
         , style_prompt                   = p_style_prompt
         , is_active                      = p_is_active
      where
            personality_id = p_personality_id
      returning
              personality_id
            , row_version
            into
              p_personality_id
            , p_row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure del
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   )
   is
   begin

        delete
          from orac_api.orac_personalities_v
         where
               personality_id = p_personality_id
      returning
              personality_id
            , row_version
            into
              p_personality_id
            , p_row_version;
   end del;

end orac_personalities_tapi;
/
--rollback drop package orac_api.orac_personalities_tapi
