--liquibase formatted sql

--changeset clive:user_preferences_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.user_preferences_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_preferences_tapi
-- Source file name :   user_preferences_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_preferences
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row              in out   orac_api.user_preferences_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.pref_key', p_row.pref_key);
      logger_user.logger.append_param(l_params, '  p_row.pref_value', p_row.pref_value);
      logger_user.logger.append_param(l_params, '  p_row.value_type', p_row.value_type);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.user_preferences_v
         (
              user_id
            , pref_key
            , pref_value
            , value_type
         )
      values
         (
              p_row.user_id
            , p_row.pref_key
            , p_row.pref_value
            , p_row.value_type
         )
      returning
              pref_id
            , row_version
            into
              p_row.pref_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type                                 := 'string'
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'ins';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_pref_key', p_pref_key);
      logger_user.logger.append_param(l_params, '  p_pref_value', p_pref_value);
      logger_user.logger.append_param(l_params, '  p_value_type', p_value_type);

      logger.log('START', l_scope, null, l_params);

      insert into orac_api.user_preferences_v
         (
              user_id
            , pref_key
            , pref_value
            , value_type
         )
      values
         (
              p_user_id
            , p_pref_key
            , p_pref_value
            , p_value_type
         )
      returning
              pref_id
            , row_version
            into
              p_pref_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row                 out   orac_api.user_preferences_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_pref_id', p_pref_id);

      logger.log('START', l_scope, null, l_params);

      select
           pref_id
         , user_id
         , pref_key
         , pref_value
         , value_type
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.pref_id
         , p_row.user_id
         , p_row.pref_key
         , p_row.pref_value
         , p_row.value_type
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.user_preferences_v
      where
            pref_id = p_pref_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id             out   orac_api.user_preferences_v.user_id%type
      , p_pref_key            out   orac_api.user_preferences_v.pref_key%type
      , p_pref_value          out   orac_api.user_preferences_v.pref_value%type
      , p_value_type          out   orac_api.user_preferences_v.value_type%type
      , p_created_on          out   orac_api.user_preferences_v.created_on%type
      , p_created_by          out   orac_api.user_preferences_v.created_by%type
      , p_updated_on          out   orac_api.user_preferences_v.updated_on%type
      , p_updated_by          out   orac_api.user_preferences_v.updated_by%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'get';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_pref_id', p_pref_id);

      logger.log('START', l_scope, null, l_params);

      select
           pref_id
         , user_id
         , pref_key
         , pref_value
         , value_type
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_pref_id
         , p_user_id
         , p_pref_key
         , p_pref_value
         , p_value_type
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.user_preferences_v
      where
            pref_id = p_pref_id;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row              in out   orac_api.user_preferences_v%rowtype
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_pref_id', p_pref_id);
      logger_user.logger.append_param(l_params, '  p_row.user_id', p_row.user_id);
      logger_user.logger.append_param(l_params, '  p_row.pref_key', p_row.pref_key);
      logger_user.logger.append_param(l_params, '  p_row.pref_value', p_row.pref_value);
      logger_user.logger.append_param(l_params, '  p_row.value_type', p_row.value_type);

      logger.log('START', l_scope, null, l_params);

      update orac_api.user_preferences_v
      set
           user_id                        = p_row.user_id
         , pref_key                       = p_row.pref_key
         , pref_value                     = p_row.pref_value
         , value_type                     = p_row.value_type
      where
            pref_id = p_pref_id
      returning
              pref_id
            , row_version
            into
              p_row.pref_id
            , p_row.row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'upd';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_pref_id', p_pref_id);
      logger_user.logger.append_param(l_params, '  p_user_id', p_user_id);
      logger_user.logger.append_param(l_params, '  p_pref_key', p_pref_key);
      logger_user.logger.append_param(l_params, '  p_pref_value', p_pref_value);
      logger_user.logger.append_param(l_params, '  p_value_type', p_value_type);

      logger.log('START', l_scope, null, l_params);

      update orac_api.user_preferences_v
      set
           user_id                        = p_user_id
         , pref_key                       = p_pref_key
         , pref_value                     = p_pref_value
         , value_type                     = p_value_type
      where
            pref_id = p_pref_id
      returning
              pref_id
            , row_version
            into
              p_pref_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure del
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is

      l_scope           logger_user.logger_logs.scope%type    := gc_unit_prefix || 'del';
      l_params          logger_user.logger.tab_param;

   begin

      -- We don't log any CLOB parameters here.
      logger_user.logger.append_param(l_params, '* p_pref_id', p_pref_id);

      logger.log('START', l_scope, null, l_params);

        delete
          from orac_api.user_preferences_v
         where
               pref_id = p_pref_id
      returning
              pref_id
            , row_version
            into
              p_pref_id
            , p_row_version;

      logger.log('END', l_scope);

   exception
      when others then
         logger_user.logger.log_error('Unhandled exception ', l_scope, null, l_params);
         raise;

   end del;

end user_preferences_tapi;
/
--rollback drop package orac_api.user_preferences_tapi
