--liquibase formatted sql

--changeset clive:user_prompt_elements_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true

create or replace package body orac_api.user_prompt_elements_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_prompt_elements_tapi
-- Source file name :   user_prompt_elements_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_prompt_elements
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                 in out   orac_api.user_prompt_elements_v%rowtype
   )
   is
   begin

      insert into orac_api.user_prompt_elements_v
         (
              user_id
            , category_code
            , prompt_element
            , weight_score
            , is_enabled
         )
      values
         (
              p_row.user_id
            , p_row.category_code
            , p_row.prompt_element
            , p_row.weight_score
            , p_row.is_enabled
         )
      returning
              element_id
            , row_version
            into
              p_row.element_id
            , p_row.row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id             in       orac_api.user_prompt_elements_v.user_id%type
      , p_category_code       in       orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element      in       orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score        in       orac_api.user_prompt_elements_v.weight_score%type                        := 1
      , p_is_enabled          in       orac_api.user_prompt_elements_v.is_enabled%type                          := 'Y'
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   )
   is
   begin

      insert into orac_api.user_prompt_elements_v
         (
              user_id
            , category_code
            , prompt_element
            , weight_score
            , is_enabled
         )
      values
         (
              p_user_id
            , p_category_code
            , p_prompt_element
            , p_weight_score
            , p_is_enabled
         )
      returning
              element_id
            , row_version
            into
              p_element_id
            , p_row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure get
   (
        p_element_id          in       orac_api.user_prompt_elements_v.element_id%type
      , p_row                    out   orac_api.user_prompt_elements_v%rowtype
   )
   is
   begin

      select
           element_id
         , user_id
         , category_code
         , prompt_element
         , weight_score
         , is_enabled
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.element_id
         , p_row.user_id
         , p_row.category_code
         , p_row.prompt_element
         , p_row.weight_score
         , p_row.is_enabled
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.user_prompt_elements_v
      where
            element_id = p_element_id;
   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure get
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id                out   orac_api.user_prompt_elements_v.user_id%type
      , p_category_code          out   orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element         out   orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score           out   orac_api.user_prompt_elements_v.weight_score%type
      , p_is_enabled             out   orac_api.user_prompt_elements_v.is_enabled%type
      , p_created_on             out   orac_api.user_prompt_elements_v.created_on%type
      , p_created_by             out   orac_api.user_prompt_elements_v.created_by%type
      , p_updated_on             out   orac_api.user_prompt_elements_v.updated_on%type
      , p_updated_by             out   orac_api.user_prompt_elements_v.updated_by%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   )
   is
   begin

      select
           element_id
         , user_id
         , category_code
         , prompt_element
         , weight_score
         , is_enabled
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_element_id
         , p_user_id
         , p_category_code
         , p_prompt_element
         , p_weight_score
         , p_is_enabled
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.user_prompt_elements_v
      where
            element_id = p_element_id;
   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_element_id          in       orac_api.user_prompt_elements_v.element_id%type
      , p_row                 in out   orac_api.user_prompt_elements_v%rowtype
   )
   is
   begin

      update orac_api.user_prompt_elements_v
      set
           user_id                        = p_row.user_id
         , category_code                  = p_row.category_code
         , prompt_element                 = p_row.prompt_element
         , weight_score                   = p_row.weight_score
         , is_enabled                     = p_row.is_enabled
      where
            element_id = p_element_id
      returning
              element_id
            , row_version
            into
              p_row.element_id
            , p_row.row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id             in       orac_api.user_prompt_elements_v.user_id%type
      , p_category_code       in       orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element      in       orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score        in       orac_api.user_prompt_elements_v.weight_score%type
      , p_is_enabled          in       orac_api.user_prompt_elements_v.is_enabled%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   )
   is
   begin

      update orac_api.user_prompt_elements_v
      set
           user_id                        = p_user_id
         , category_code                  = p_category_code
         , prompt_element                 = p_prompt_element
         , weight_score                   = p_weight_score
         , is_enabled                     = p_is_enabled
      where
            element_id = p_element_id
      returning
              element_id
            , row_version
            into
              p_element_id
            , p_row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure del
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   )
   is
   begin

        delete
          from orac_api.user_prompt_elements_v
         where
               element_id = p_element_id
      returning
              element_id
            , row_version
            into
              p_element_id
            , p_row_version;
   end del;

end user_prompt_elements_tapi;
/
--rollback drop package orac_api.user_prompt_elements_tapi
