--liquibase formatted sql

--changeset clive:users_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package body orac_api.users_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   users_tapi
-- Source file name :   users_tapi.sql
-- Purpose          :   Table API (TAPI) for table users
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row               in out   orac_api.users_v%rowtype
   )
   is
   begin

      insert into orac_api.users_v
         (
              username
            , display_name
            , email
            , is_active
         )
      values
         (
              p_row.username
            , p_row.display_name
            , p_row.email
            , p_row.is_active
         )
      returning
              user_id
            , row_version
            into
              p_row.user_id
            , p_row.row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_username          in       orac_api.users_v.username%type
      , p_display_name      in       orac_api.users_v.display_name%type
      , p_email             in       orac_api.users_v.email%type
      , p_is_active         in       orac_api.users_v.is_active%type                                            := 'Y'
      , p_row_version          out   orac_api.users_v.row_version%type
   )
   is
   begin

      insert into orac_api.users_v
         (
              username
            , display_name
            , email
            , is_active
         )
      values
         (
              p_username
            , p_display_name
            , p_email
            , p_is_active
         )
      returning
              user_id
            , row_version
            into
              g_row.user_id
            , p_row_version;
   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure get
   (
        p_user_id           in       orac_api.users_v.user_id%type
      , p_row                  out   orac_api.users_v%rowtype
   )
   is
   begin

      select
           user_id
         , username
         , display_name
         , email
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.user_id
         , p_row.username
         , p_row.display_name
         , p_row.email
         , p_row.is_active
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.users_v
      where
            user_id = p_user_id;
   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure get
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_username             out   orac_api.users_v.username%type
      , p_display_name         out   orac_api.users_v.display_name%type
      , p_email                out   orac_api.users_v.email%type
      , p_is_active            out   orac_api.users_v.is_active%type
      , p_created_on           out   orac_api.users_v.created_on%type
      , p_created_by           out   orac_api.users_v.created_by%type
      , p_updated_on           out   orac_api.users_v.updated_on%type
      , p_updated_by           out   orac_api.users_v.updated_by%type
      , p_row_version          out   orac_api.users_v.row_version%type
   )
   is
   begin

      select
           user_id
         , username
         , display_name
         , email
         , is_active
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_user_id
         , p_username
         , p_display_name
         , p_email
         , p_is_active
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.users_v
      where
            user_id = p_user_id;
   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_user_id           in       orac_api.users_v.user_id%type
      , p_row               in out   orac_api.users_v%rowtype
   )
   is
   begin

      update orac_api.users_v
      set
           username                       = p_row.username
         , display_name                   = p_row.display_name
         , email                          = p_row.email
         , is_active                      = p_row.is_active
      where
            user_id = p_user_id
      returning
              user_id
            , row_version
            into
              p_row.user_id
            , p_row.row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_username          in       orac_api.users_v.username%type
      , p_display_name      in       orac_api.users_v.display_name%type
      , p_email             in       orac_api.users_v.email%type
      , p_is_active         in       orac_api.users_v.is_active%type
      , p_row_version          out   orac_api.users_v.row_version%type
   )
   is
   begin

      update orac_api.users_v
      set
           username                       = p_username
         , display_name                   = p_display_name
         , email                          = p_email
         , is_active                      = p_is_active
      where
            user_id = p_user_id
      returning
              user_id
            , row_version
            into
              p_user_id
            , p_row_version;
   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure del
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_row_version          out   orac_api.users_v.row_version%type
   )
   is
   begin

        delete
          from orac_api.users_v
         where
               user_id = p_user_id
      returning
              user_id
            , row_version
            into
              p_user_id
            , p_row_version;
   end del;

end users_tapi;
/
--rollback drop package body orac_api.users_tapi;