--liquibase formatted sql

--changeset clive:user_preferences_tapi_create_body stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package body orac_api.user_preferences_tapi
as
--------------------------------------------------------------------------------
--
-- Copyright(C) 2026, Clive Bostock`s Software Emporium
-- All Rights Reserved
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_preferences_tapi
-- Source file name :   user_preferences_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_preferences
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   gc_unit_prefix       constant varchar(64) := lower($$pls_unit) || '.';

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row              in out   orac_api.user_preferences_v%rowtype
   )
   is
   begin
      insert into orac_api.user_preferences_v
         (
              user_id
            , pref_key
            , pref_value
            , value_type
         )
      values
         (
              p_row.user_id
            , p_row.pref_key
            , p_row.pref_value
            , p_row.value_type
         )
      ;

      select pref_id
           , row_version
        into p_row.pref_id
           , p_row.row_version
        from orac_api.user_preferences_v
       where user_id = p_row.user_id
         and pref_key = p_row.pref_key;

   end ins;


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type                                 := 'string'
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is
   begin
      insert into orac_api.user_preferences_v
         (
              user_id
            , pref_key
            , pref_value
            , value_type
         )
      values
         (
              p_user_id
            , p_pref_key
            , p_pref_value
            , p_value_type
         )
      ;

      select pref_id
           , row_version
        into p_pref_id
           , p_row_version
        from orac_api.user_preferences_v
       where user_id = p_user_id
         and pref_key = p_pref_key;

   end ins;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row                 out   orac_api.user_preferences_v%rowtype
   )
   is
   begin
      select
           pref_id
         , user_id
         , pref_key
         , pref_value
         , value_type
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_row.pref_id
         , p_row.user_id
         , p_row.pref_key
         , p_row.pref_value
         , p_row.value_type
         , p_row.created_on
         , p_row.created_by
         , p_row.updated_on
         , p_row.updated_by
         , p_row.row_version
       from orac_api.user_preferences_v
      where
            pref_id = p_pref_id;

   end get;


   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id             out   orac_api.user_preferences_v.user_id%type
      , p_pref_key            out   orac_api.user_preferences_v.pref_key%type
      , p_pref_value          out   orac_api.user_preferences_v.pref_value%type
      , p_value_type          out   orac_api.user_preferences_v.value_type%type
      , p_created_on          out   orac_api.user_preferences_v.created_on%type
      , p_created_by          out   orac_api.user_preferences_v.created_by%type
      , p_updated_on          out   orac_api.user_preferences_v.updated_on%type
      , p_updated_by          out   orac_api.user_preferences_v.updated_by%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is
   begin
      select
           pref_id
         , user_id
         , pref_key
         , pref_value
         , value_type
         , created_on
         , created_by
         , updated_on
         , updated_by
         , row_version
        into
           p_pref_id
         , p_user_id
         , p_pref_key
         , p_pref_value
         , p_value_type
         , p_created_on
         , p_created_by
         , p_updated_on
         , p_updated_by
         , p_row_version
       from orac_api.user_preferences_v
      where
            pref_id = p_pref_id;

   end get;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row              in out   orac_api.user_preferences_v%rowtype
   )
   is
   begin
      update orac_api.user_preferences_v
      set
           user_id                        = p_row.user_id
         , pref_key                       = p_row.pref_key
         , pref_value                     = p_row.pref_value
         , value_type                     = p_row.value_type
      where
            pref_id = p_pref_id;

      p_row.pref_id := p_pref_id;

      select row_version
        into p_row.row_version
        from orac_api.user_preferences_v
       where pref_id = p_pref_id;

   end upd;


   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is
   begin
      update orac_api.user_preferences_v
      set
           user_id                        = p_user_id
         , pref_key                       = p_pref_key
         , pref_value                     = p_pref_value
         , value_type                     = p_value_type
      where
            pref_id = p_pref_id;

      select row_version
        into p_row_version
        from orac_api.user_preferences_v
       where pref_id = p_pref_id;

   end upd;


   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure del
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   )
   is
   begin
      select row_version
        into p_row_version
        from orac_api.user_preferences_v
       where pref_id = p_pref_id;

        delete
          from orac_api.user_preferences_v
         where
               pref_id = p_pref_id;

   end del;

end user_preferences_tapi;
/
--rollback drop package body orac_api.user_preferences_tapi;