--liquibase formatted sql

--changeset clive:conversations_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true

create or replace package orac_api.conversations_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   conversations_tapi
-- Source file name :   conversations_tapi.sql
-- Purpose          :   Table API (TAPI) for table conversations
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.conversations_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                  in out   orac_api.conversations_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id              in       orac_api.conversations_v.user_id%type
      , p_session_id           in       orac_api.conversations_v.session_id%type
      , p_llm_id               in       orac_api.conversations_v.llm_id%type
      , p_title                in       orac_api.conversations_v.title%type                                     := 'Brief exchange...'
      , p_state                in       orac_api.conversations_v.state%type                                     := 'open'
      , p_row_version             out   orac_api.conversations_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure get
   (
        p_conversation_id      in       orac_api.conversations_v.conversation_id%type
      , p_row                     out   orac_api.conversations_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure get
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id                 out   orac_api.conversations_v.user_id%type
      , p_session_id              out   orac_api.conversations_v.session_id%type
      , p_llm_id                  out   orac_api.conversations_v.llm_id%type
      , p_title                   out   orac_api.conversations_v.title%type
      , p_state                   out   orac_api.conversations_v.state%type
      , p_created_on              out   orac_api.conversations_v.created_on%type
      , p_created_by              out   orac_api.conversations_v.created_by%type
      , p_updated_on              out   orac_api.conversations_v.updated_on%type
      , p_updated_by              out   orac_api.conversations_v.updated_by%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_conversation_id      in       orac_api.conversations_v.conversation_id%type
      , p_row                  in out   orac_api.conversations_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_user_id              in       orac_api.conversations_v.user_id%type
      , p_session_id           in       orac_api.conversations_v.session_id%type
      , p_llm_id               in       orac_api.conversations_v.llm_id%type
      , p_title                in       orac_api.conversations_v.title%type
      , p_state                in       orac_api.conversations_v.state%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.conversations
   -----------------------------------------------------------------------------
   procedure del
   (
        p_conversation_id      in out   orac_api.conversations_v.conversation_id%type
      , p_row_version             out   orac_api.conversations_v.row_version%type
   );

end conversations_tapi;
/
--rollback drop package orac_api.conversations_tapi
