--liquibase formatted sql

--changeset clive:devices_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true

create or replace package orac_api.devices_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   devices_tapi
-- Source file name :   devices_tapi.sql
-- Purpose          :   Table API (TAPI) for table devices
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.devices_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row              in out   orac_api.devices_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id          in       orac_api.devices_v.user_id%type
      , p_host_name        in       orac_api.devices_v.host_name%type
      , p_is_active        in       orac_api.devices_v.is_active%type                                           := 'Y'
      , p_row_version         out   orac_api.devices_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure get
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row                 out   orac_api.devices_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure get
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id             out   orac_api.devices_v.user_id%type
      , p_host_name           out   orac_api.devices_v.host_name%type
      , p_is_active           out   orac_api.devices_v.is_active%type
      , p_created_on          out   orac_api.devices_v.created_on%type
      , p_created_by          out   orac_api.devices_v.created_by%type
      , p_updated_on          out   orac_api.devices_v.updated_on%type
      , p_updated_by          out   orac_api.devices_v.updated_by%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_device_id        in       orac_api.devices_v.device_id%type
      , p_row              in out   orac_api.devices_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_user_id          in       orac_api.devices_v.user_id%type
      , p_host_name        in       orac_api.devices_v.host_name%type
      , p_is_active        in       orac_api.devices_v.is_active%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.devices
   -----------------------------------------------------------------------------
   procedure del
   (
        p_device_id        in out   orac_api.devices_v.device_id%type
      , p_row_version         out   orac_api.devices_v.row_version%type
   );

end devices_tapi;
/
--rollback drop package orac_api.devices_tapi
