--liquibase formatted sql

--changeset clive:llm_registry_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.llm_registry_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   llm_registry_tapi
-- Source file name :   llm_registry_tapi.sql
-- Purpose          :   Table API (TAPI) for table llm_registry
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.llm_registry_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                     in out   orac_api.llm_registry_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_name                    in       orac_api.llm_registry_v.name%type
      , p_provider                in       orac_api.llm_registry_v.provider%type
      , p_model                   in       orac_api.llm_registry_v.model%type
      , p_context_policy          in       orac_api.llm_registry_v.context_policy%type
                                          := 'unresolved'
      , p_max_context_tokens      in       orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled              in       orac_api.llm_registry_v.is_enabled%type                              := 'Y'
      , p_properties              in       orac_api.llm_registry_v.properties%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure get
   (
        p_llm_id                  in       orac_api.llm_registry_v.llm_id%type
      , p_row                        out   orac_api.llm_registry_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure get
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_name                       out   orac_api.llm_registry_v.name%type
      , p_provider                   out   orac_api.llm_registry_v.provider%type
      , p_model                      out   orac_api.llm_registry_v.model%type
      , p_context_policy             out   orac_api.llm_registry_v.context_policy%type
      , p_max_context_tokens         out   orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled                 out   orac_api.llm_registry_v.is_enabled%type
      , p_properties                 out   orac_api.llm_registry_v.properties%type
      , p_created_on                 out   orac_api.llm_registry_v.created_on%type
      , p_created_by                 out   orac_api.llm_registry_v.created_by%type
      , p_updated_on                 out   orac_api.llm_registry_v.updated_on%type
      , p_updated_by                 out   orac_api.llm_registry_v.updated_by%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_llm_id                  in       orac_api.llm_registry_v.llm_id%type
      , p_row                     in out   orac_api.llm_registry_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_name                    in       orac_api.llm_registry_v.name%type
      , p_provider                in       orac_api.llm_registry_v.provider%type
      , p_model                   in       orac_api.llm_registry_v.model%type
      , p_context_policy          in       orac_api.llm_registry_v.context_policy%type
                                          := 'unresolved'
      , p_max_context_tokens      in       orac_api.llm_registry_v.max_context_tokens%type
      , p_is_enabled              in       orac_api.llm_registry_v.is_enabled%type
      , p_properties              in       orac_api.llm_registry_v.properties%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.llm_registry
   -----------------------------------------------------------------------------
   procedure del
   (
        p_llm_id                  in out   orac_api.llm_registry_v.llm_id%type
      , p_row_version                out   orac_api.llm_registry_v.row_version%type
   );

end llm_registry_tapi;
/
--rollback drop package orac_api.llm_registry_tapi;