--liquibase formatted sql

--changeset clive:messages_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.messages_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   messages_tapi
-- Source file name :   messages_tapi.sql
-- Purpose          :   Table API (TAPI) for table messages
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.messages_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                  in out   orac_api.messages_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id      in       orac_api.messages_v.conversation_id%type
      , p_message_type         in       orac_api.messages_v.message_type%type
      , p_turn_index           in       orac_api.messages_v.turn_index%type
      , p_role                 in       orac_api.messages_v.role%type
      , p_content              in       orac_api.messages_v.content%type
      , p_tokens_used          in       orac_api.messages_v.tokens_used%type
      , p_meta                 in       orac_api.messages_v.meta%type
      , p_llm_id               in       orac_api.messages_v.llm_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure get
   (
        p_message_id           in       orac_api.messages_v.message_id%type
      , p_row                     out   orac_api.messages_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure get
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id         out   orac_api.messages_v.conversation_id%type
      , p_message_type            out   orac_api.messages_v.message_type%type
      , p_turn_index              out   orac_api.messages_v.turn_index%type
      , p_role                    out   orac_api.messages_v.role%type
      , p_content                 out   orac_api.messages_v.content%type
      , p_tokens_used             out   orac_api.messages_v.tokens_used%type
      , p_meta                    out   orac_api.messages_v.meta%type
      , p_llm_id                  out   orac_api.messages_v.llm_id%type
      , p_created_on              out   orac_api.messages_v.created_on%type
      , p_created_by              out   orac_api.messages_v.created_by%type
      , p_updated_on              out   orac_api.messages_v.updated_on%type
      , p_updated_by              out   orac_api.messages_v.updated_by%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_message_id           in       orac_api.messages_v.message_id%type
      , p_row                  in out   orac_api.messages_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_conversation_id      in       orac_api.messages_v.conversation_id%type
      , p_message_type         in       orac_api.messages_v.message_type%type
      , p_turn_index           in       orac_api.messages_v.turn_index%type
      , p_role                 in       orac_api.messages_v.role%type
      , p_content              in       orac_api.messages_v.content%type
      , p_tokens_used          in       orac_api.messages_v.tokens_used%type
      , p_meta                 in       orac_api.messages_v.meta%type
      , p_llm_id               in       orac_api.messages_v.llm_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.messages
   -----------------------------------------------------------------------------
   procedure del
   (
        p_message_id           in out   orac_api.messages_v.message_id%type
      , p_row_version             out   orac_api.messages_v.row_version%type
   );

end messages_tapi;
/
--rollback drop package orac_api.messages_tapi;