--liquibase formatted sql

--changeset clive:message_embeddings_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.message_embeddings_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   message_embeddings_tapi
-- Source file name :   message_embeddings_tapi.sql
-- Purpose          :   Table API (TAPI) for table message_embeddings
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.message_embeddings_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                     in out   orac_api.message_embeddings_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id              in       orac_api.message_embeddings_v.message_id%type
      , p_chunk_index             in       orac_api.message_embeddings_v.chunk_index%type                       := 1
      , p_span_start              in       orac_api.message_embeddings_v.span_start%type
      , p_span_end                in       orac_api.message_embeddings_v.span_end%type
      , p_lossless_text           in       orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot        in       orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding               in       orac_api.message_embeddings_v.embedding%type
      , p_embedding_model         in       orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider      in       orac_api.message_embeddings_v.embedding_provider%type                := 'oracle'
      , p_distance_metric         in       orac_api.message_embeddings_v.distance_metric%type                   := 'COSINE'
      , p_tokens_used             in       orac_api.message_embeddings_v.tokens_used%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure get
   (
        p_emb_id                  in       orac_api.message_embeddings_v.emb_id%type
      , p_row                        out   orac_api.message_embeddings_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure get
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id                 out   orac_api.message_embeddings_v.message_id%type
      , p_chunk_index                out   orac_api.message_embeddings_v.chunk_index%type
      , p_span_start                 out   orac_api.message_embeddings_v.span_start%type
      , p_span_end                   out   orac_api.message_embeddings_v.span_end%type
      , p_lossless_text              out   orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot           out   orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding                  out   orac_api.message_embeddings_v.embedding%type
      , p_embedding_model            out   orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider         out   orac_api.message_embeddings_v.embedding_provider%type
      , p_distance_metric            out   orac_api.message_embeddings_v.distance_metric%type
      , p_tokens_used                out   orac_api.message_embeddings_v.tokens_used%type
      , p_created_on                 out   orac_api.message_embeddings_v.created_on%type
      , p_created_by                 out   orac_api.message_embeddings_v.created_by%type
      , p_updated_on                 out   orac_api.message_embeddings_v.updated_on%type
      , p_updated_by                 out   orac_api.message_embeddings_v.updated_by%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_emb_id                  in       orac_api.message_embeddings_v.emb_id%type
      , p_row                     in out   orac_api.message_embeddings_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_message_id              in       orac_api.message_embeddings_v.message_id%type
      , p_chunk_index             in       orac_api.message_embeddings_v.chunk_index%type
      , p_span_start              in       orac_api.message_embeddings_v.span_start%type
      , p_span_end                in       orac_api.message_embeddings_v.span_end%type
      , p_lossless_text           in       orac_api.message_embeddings_v.lossless_text%type
      , p_content_snapshot        in       orac_api.message_embeddings_v.content_snapshot%type
      , p_embedding               in       orac_api.message_embeddings_v.embedding%type
      , p_embedding_model         in       orac_api.message_embeddings_v.embedding_model%type
      , p_embedding_provider      in       orac_api.message_embeddings_v.embedding_provider%type
      , p_distance_metric         in       orac_api.message_embeddings_v.distance_metric%type
      , p_tokens_used             in       orac_api.message_embeddings_v.tokens_used%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.message_embeddings
   -----------------------------------------------------------------------------
   procedure del
   (
        p_emb_id                  in out   orac_api.message_embeddings_v.emb_id%type
      , p_row_version                out   orac_api.message_embeddings_v.row_version%type
   );

end message_embeddings_tapi;
/
--rollback drop package orac_api.message_embeddings_tapi;