--liquibase formatted sql

--changeset clive:orac_personalities_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.orac_personalities_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   orac_personalities_tapi
-- Source file name :   orac_personalities_tapi.sql
-- Purpose          :   Table API (TAPI) for table orac_personalities
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.orac_personalities_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                      in out   orac_api.orac_personalities_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_personality_code         in       orac_api.orac_personalities_v.personality_code%type
      , p_personality_name         in       orac_api.orac_personalities_v.personality_name%type
      , p_description              in       orac_api.orac_personalities_v.description%type
      , p_attitude_base_level      in       orac_api.orac_personalities_v.attitude_base_level%type              := 1
      , p_sarcasm_level            in       orac_api.orac_personalities_v.sarcasm_level%type                    := 1
      , p_verbosity_level          in       orac_api.orac_personalities_v.verbosity_level%type                  := 1
      , p_allow_humour             in       orac_api.orac_personalities_v.allow_humour%type                     := true
      , p_allow_critique           in       orac_api.orac_personalities_v.allow_critique%type                   := true
      , p_enforce_precision        in       orac_api.orac_personalities_v.enforce_precision%type                := true
      , p_admit_uncertainty        in       orac_api.orac_personalities_v.admit_uncertainty%type                := true
      , p_packaged_persona         in       orac_api.orac_personalities_v.packaged_persona%type                 := false
      , p_model_preset_id          in       orac_api.orac_personalities_v.model_preset_id%type                  := null
      , p_system_prompt            in       orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt             in       orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                in       orac_api.orac_personalities_v.is_active%type                        := true
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure get
   (
        p_personality_id           in       orac_api.orac_personalities_v.personality_id%type
      , p_row                         out   orac_api.orac_personalities_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure get
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_personality_code            out   orac_api.orac_personalities_v.personality_code%type
      , p_personality_name            out   orac_api.orac_personalities_v.personality_name%type
      , p_description                 out   orac_api.orac_personalities_v.description%type
      , p_attitude_base_level         out   orac_api.orac_personalities_v.attitude_base_level%type
      , p_sarcasm_level               out   orac_api.orac_personalities_v.sarcasm_level%type
      , p_verbosity_level             out   orac_api.orac_personalities_v.verbosity_level%type
      , p_allow_humour                out   orac_api.orac_personalities_v.allow_humour%type
      , p_allow_critique              out   orac_api.orac_personalities_v.allow_critique%type
      , p_enforce_precision           out   orac_api.orac_personalities_v.enforce_precision%type
      , p_admit_uncertainty           out   orac_api.orac_personalities_v.admit_uncertainty%type
      , p_packaged_persona            out   orac_api.orac_personalities_v.packaged_persona%type
      , p_model_preset_id             out   orac_api.orac_personalities_v.model_preset_id%type
      , p_system_prompt               out   orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt                out   orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                   out   orac_api.orac_personalities_v.is_active%type
      , p_created_on                  out   orac_api.orac_personalities_v.created_on%type
      , p_created_by                  out   orac_api.orac_personalities_v.created_by%type
      , p_updated_on                  out   orac_api.orac_personalities_v.updated_on%type
      , p_updated_by                  out   orac_api.orac_personalities_v.updated_by%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_personality_id           in       orac_api.orac_personalities_v.personality_id%type
      , p_row                      in out   orac_api.orac_personalities_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_personality_code         in       orac_api.orac_personalities_v.personality_code%type
      , p_personality_name         in       orac_api.orac_personalities_v.personality_name%type
      , p_description              in       orac_api.orac_personalities_v.description%type
      , p_attitude_base_level      in       orac_api.orac_personalities_v.attitude_base_level%type
      , p_sarcasm_level            in       orac_api.orac_personalities_v.sarcasm_level%type
      , p_verbosity_level          in       orac_api.orac_personalities_v.verbosity_level%type
      , p_allow_humour             in       orac_api.orac_personalities_v.allow_humour%type
      , p_allow_critique           in       orac_api.orac_personalities_v.allow_critique%type
      , p_enforce_precision        in       orac_api.orac_personalities_v.enforce_precision%type
      , p_admit_uncertainty        in       orac_api.orac_personalities_v.admit_uncertainty%type
      , p_packaged_persona         in       orac_api.orac_personalities_v.packaged_persona%type
      , p_model_preset_id          in       orac_api.orac_personalities_v.model_preset_id%type                  := null
      , p_system_prompt            in       orac_api.orac_personalities_v.system_prompt%type
      , p_style_prompt             in       orac_api.orac_personalities_v.style_prompt%type
      , p_is_active                in       orac_api.orac_personalities_v.is_active%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.orac_personalities
   -----------------------------------------------------------------------------
   procedure del
   (
        p_personality_id           in out   orac_api.orac_personalities_v.personality_id%type
      , p_row_version                 out   orac_api.orac_personalities_v.row_version%type
   );

end orac_personalities_tapi;
/
--rollback drop package orac_api.orac_personalities_tapi;