--liquibase formatted sql

--changeset clive:users_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true

create or replace package orac_api.users_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   users_tapi
-- Source file name :   users_tapi.sql
-- Purpose          :   Table API (TAPI) for table users
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.users_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row               in out   orac_api.users_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_username          in       orac_api.users_v.username%type
      , p_display_name      in       orac_api.users_v.display_name%type
      , p_email             in       orac_api.users_v.email%type
      , p_is_active         in       orac_api.users_v.is_active%type                                            := 'Y'
      , p_row_version          out   orac_api.users_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure get
   (
        p_user_id           in       orac_api.users_v.user_id%type
      , p_row                  out   orac_api.users_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure get
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_username             out   orac_api.users_v.username%type
      , p_display_name         out   orac_api.users_v.display_name%type
      , p_email                out   orac_api.users_v.email%type
      , p_is_active            out   orac_api.users_v.is_active%type
      , p_created_on           out   orac_api.users_v.created_on%type
      , p_created_by           out   orac_api.users_v.created_by%type
      , p_updated_on           out   orac_api.users_v.updated_on%type
      , p_updated_by           out   orac_api.users_v.updated_by%type
      , p_row_version          out   orac_api.users_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_user_id           in       orac_api.users_v.user_id%type
      , p_row               in out   orac_api.users_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_username          in       orac_api.users_v.username%type
      , p_display_name      in       orac_api.users_v.display_name%type
      , p_email             in       orac_api.users_v.email%type
      , p_is_active         in       orac_api.users_v.is_active%type
      , p_row_version          out   orac_api.users_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.users
   -----------------------------------------------------------------------------
   procedure del
   (
        p_user_id           in out   orac_api.users_v.user_id%type
      , p_row_version          out   orac_api.users_v.row_version%type
   );

end users_tapi;
/
--rollback drop package orac_api.users_tapi
