--liquibase formatted sql

--changeset clive:user_synonyms_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.user_synonyms_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_synonyms_tapi
-- Source file name :   user_synonyms_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_synonyms
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.user_synonyms_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_alias_type       in       orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in       orac_api.user_synonyms_v.alias_value%type
      , p_row              in out   orac_api.user_synonyms_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_user_id          in       orac_api.user_synonyms_v.user_id%type
      , p_alias_type       in out   orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in out   orac_api.user_synonyms_v.alias_value%type
      , p_is_active        in       orac_api.user_synonyms_v.is_active%type                                     := 'Y'
      , p_row_version         out   orac_api.user_synonyms_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure get
   (
        p_alias_type       in       orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in       orac_api.user_synonyms_v.alias_value%type
      , p_row                 out   orac_api.user_synonyms_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure get
   (
        p_user_id             out   orac_api.user_synonyms_v.user_id%type
      , p_alias_type       in out   orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in out   orac_api.user_synonyms_v.alias_value%type
      , p_is_active           out   orac_api.user_synonyms_v.is_active%type
      , p_created_on          out   orac_api.user_synonyms_v.created_on%type
      , p_created_by          out   orac_api.user_synonyms_v.created_by%type
      , p_updated_on          out   orac_api.user_synonyms_v.updated_on%type
      , p_updated_by          out   orac_api.user_synonyms_v.updated_by%type
      , p_row_version         out   orac_api.user_synonyms_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_alias_type       in       orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in       orac_api.user_synonyms_v.alias_value%type
      , p_row              in out   orac_api.user_synonyms_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_user_id          in       orac_api.user_synonyms_v.user_id%type
      , p_alias_type       in out   orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in out   orac_api.user_synonyms_v.alias_value%type
      , p_is_active        in       orac_api.user_synonyms_v.is_active%type
      , p_row_version         out   orac_api.user_synonyms_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_synonyms
   -----------------------------------------------------------------------------
   procedure del
   (
        p_alias_type       in out   orac_api.user_synonyms_v.alias_type%type
      , p_alias_value      in out   orac_api.user_synonyms_v.alias_value%type
      , p_row_version         out   orac_api.user_synonyms_v.row_version%type
   );

end user_synonyms_tapi;
/
--rollback drop package orac_api.user_synonyms_tapi;