--liquibase formatted sql

--changeset clive:user_prompt_elements_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true

create or replace package orac_api.user_prompt_elements_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_prompt_elements_tapi
-- Source file name :   user_prompt_elements_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_prompt_elements
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.user_prompt_elements_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row                 in out   orac_api.user_prompt_elements_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id             in       orac_api.user_prompt_elements_v.user_id%type
      , p_category_code       in       orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element      in       orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score        in       orac_api.user_prompt_elements_v.weight_score%type                        := 1
      , p_is_enabled          in       orac_api.user_prompt_elements_v.is_enabled%type                          := 'Y'
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure get
   (
        p_element_id          in       orac_api.user_prompt_elements_v.element_id%type
      , p_row                    out   orac_api.user_prompt_elements_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure get
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id                out   orac_api.user_prompt_elements_v.user_id%type
      , p_category_code          out   orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element         out   orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score           out   orac_api.user_prompt_elements_v.weight_score%type
      , p_is_enabled             out   orac_api.user_prompt_elements_v.is_enabled%type
      , p_created_on             out   orac_api.user_prompt_elements_v.created_on%type
      , p_created_by             out   orac_api.user_prompt_elements_v.created_by%type
      , p_updated_on             out   orac_api.user_prompt_elements_v.updated_on%type
      , p_updated_by             out   orac_api.user_prompt_elements_v.updated_by%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_element_id          in       orac_api.user_prompt_elements_v.element_id%type
      , p_row                 in out   orac_api.user_prompt_elements_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_user_id             in       orac_api.user_prompt_elements_v.user_id%type
      , p_category_code       in       orac_api.user_prompt_elements_v.category_code%type
      , p_prompt_element      in       orac_api.user_prompt_elements_v.prompt_element%type
      , p_weight_score        in       orac_api.user_prompt_elements_v.weight_score%type
      , p_is_enabled          in       orac_api.user_prompt_elements_v.is_enabled%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_prompt_elements
   -----------------------------------------------------------------------------
   procedure del
   (
        p_element_id          in out   orac_api.user_prompt_elements_v.element_id%type
      , p_row_version            out   orac_api.user_prompt_elements_v.row_version%type
   );

end user_prompt_elements_tapi;
/
--rollback drop package orac_api.user_prompt_elements_tapi
