--liquibase formatted sql

--changeset clive:user_preferences_tapi_create_spec stripComments:false endDelimiter:/ runOnChange:true context:core labels:core splitStatements:false

create or replace package orac_api.user_preferences_tapi
authid definer
as
--------------------------------------------------------------------------------
--
-- Copyright (c) 2026 Clive Bostock`s Software Emporium
-- SPDX-License-Identifier: MIT
--
--------------------------------------------------------------------------------
-- Application      :   Orac
-- Domain           :   undefined
-- Package          :   user_preferences_tapi
-- Source file name :   user_preferences_tapi.sql
-- Purpose          :   Table API (TAPI) for table user_preferences
--
-- HAS COMMITS      :   NO
-- HAS ROLLBACKS    :   NO
--
-- Notes            :   Generated using OraTAPI 2.9.0
--           `      :   Generated by clive on 25-Apr-2026
--  
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC TYPES AND GLOBALS >--------------------------------------------------

   subtype ty_row is orac_api.user_preferences_v%rowtype;

   g_row ty_row;

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--< PUBLIC METHODS >------------------------------------------------------------


   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_row              in out   orac_api.user_preferences_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Insert TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure ins
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type                                 := 'string'
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row                 out   orac_api.user_preferences_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Select TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure get
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id             out   orac_api.user_preferences_v.user_id%type
      , p_pref_key            out   orac_api.user_preferences_v.pref_key%type
      , p_pref_value          out   orac_api.user_preferences_v.pref_value%type
      , p_value_type          out   orac_api.user_preferences_v.value_type%type
      , p_created_on          out   orac_api.user_preferences_v.created_on%type
      , p_created_by          out   orac_api.user_preferences_v.created_by%type
      , p_updated_on          out   orac_api.user_preferences_v.updated_on%type
      , p_updated_by          out   orac_api.user_preferences_v.updated_by%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in       orac_api.user_preferences_v.pref_id%type
      , p_row              in out   orac_api.user_preferences_v%rowtype
   );



   -----------------------------------------------------------------------------
   -- Update TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure upd
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_user_id          in       orac_api.user_preferences_v.user_id%type
      , p_pref_key         in       orac_api.user_preferences_v.pref_key%type
      , p_pref_value       in       orac_api.user_preferences_v.pref_value%type
      , p_value_type       in       orac_api.user_preferences_v.value_type%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   );



   -----------------------------------------------------------------------------
   -- Delete TAPI for: orac.user_preferences
   -----------------------------------------------------------------------------
   procedure del
   (
        p_pref_id          in out   orac_api.user_preferences_v.pref_id%type
      , p_row_version         out   orac_api.user_preferences_v.row_version%type
   );

end user_preferences_tapi;
/
--rollback drop package orac_api.user_preferences_tapi;