--liquibase formatted sql

--changeset clive:create_table_orac_core_table_conversations context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'CONVERSATIONS';
-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac_core.conversations
(
  conversation_id number generated by default on null as identity not null,
  user_id         number not null,
  session_id      varchar2(64 byte) not null,
  llm_id          number,
  title           varchar2(200 byte) default on null 'Brief exchange...',
  state           varchar2(20 byte) default 'open' not null,
  created_on      timestamp default systimestamp not null,
  created_by      varchar2(128 byte) default coalesce(
                    sys_context('apex$session', 'app_user'),
                    sys_context('userenv', 'proxy_user'),
                    sys_context('userenv', 'session_user'),
                    user
                  ) not null,
  updated_on      timestamp,
  updated_by      varchar2(128 byte),
  row_version     number default 1 not null
)
;

--rollback drop table orac_core.conversations purge;
