-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac.conversations
(
  conversation_id number generated by default on null as identity not null,
  user_id         number not null,
  session_id      varchar2(64 byte) not null,
  llm_id          number,
  title           varchar2(200 byte) default on null 'Brief exchange...',
  state           varchar2(20 byte) default 'open' not null,
  created_on      timestamp default systimestamp not null,
  created_by      varchar2(128 byte) default coalesce(
                    sys_context('apex$session', 'app_user'),
                    sys_context('userenv', 'proxy_user'),
                    sys_context('userenv', 'session_user'),
                    user
                  ) not null,
  updated_on      timestamp,
  updated_by      varchar2(128 byte),
  row_version     number default 1 not null
)
;
