--liquibase formatted sql

--changeset clive:create_table_orac_core_knowledge_scopes context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_SCOPES';
-- __author__: clive
-- __date__: 2026-07-20
-- __description__: canonical relational project and plugin knowledge scopes

create table orac_core.knowledge_scopes
(
  knowledge_scope_id number generated by default on null as identity not null,
  scope_type         varchar2(20 char) not null,
  project_id         number,
  plugin_registry_id number,
  created_by         varchar2(128 char) default coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  created_on         timestamp with time zone default systimestamp not null,
  updated_by         varchar2(128 char) default coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  updated_on         timestamp with time zone default systimestamp not null,
  row_version        number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_scopes purge;

--changeset clive:add_knowledge_scope_id_to_source_objects context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tab_columns where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_SOURCE_OBJECTS' and column_name = 'KNOWLEDGE_SCOPE_ID';
alter table orac_core.knowledge_source_objects add knowledge_scope_id number;
--rollback alter table orac_core.knowledge_source_objects drop column knowledge_scope_id;
