--liquibase formatted sql

--changeset clive:create_table_orac_core_knowledge_source_objects context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_SOURCE_OBJECTS';
create table orac_core.knowledge_source_objects
(
  source_object_id       number generated by default on null as identity not null,
  source_type            varchar2(50 char) not null,
  source_reference       varchar2(700 char) not null,
  parent_source_reference varchar2(1000 char),
  target_scope_type      varchar2(50 char) not null,
  target_scope_key       varchar2(200 char) not null,
  created_by             varchar2(128 char) default coalesce(
                           sys_context('apex$session', 'app_user'),
                           sys_context('userenv', 'proxy_user'),
                           sys_context('userenv', 'session_user'),
                           user
                         ) not null,
  created_on             timestamp with time zone default systimestamp not null,
  updated_by             varchar2(128 char) default coalesce(
                           sys_context('apex$session', 'app_user'),
                           sys_context('userenv', 'proxy_user'),
                           sys_context('userenv', 'session_user'),
                           user
                         ) not null,
  updated_on             timestamp with time zone default systimestamp not null,
  row_version            number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_source_objects purge;

--changeset clive:create_table_orac_core_knowledge_documents context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_DOCUMENTS';
create table orac_core.knowledge_documents
(
  document_id             number generated by default on null as identity not null,
  source_object_id        number not null,
  target_scope_type       varchar2(50 char) not null,
  target_scope_key        varchar2(200 char) not null,
  title                   varchar2(500 char),
  current_document_version_id number,
  created_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  created_on              timestamp with time zone default systimestamp not null,
  updated_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  updated_on              timestamp with time zone default systimestamp not null,
  row_version             number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_documents purge;

--changeset clive:create_table_orac_core_knowledge_document_versions context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_DOCUMENT_VERSIONS';
create table orac_core.knowledge_document_versions
(
  document_version_id number generated by default on null as identity not null,
  document_id         number not null,
  source_object_id    number not null,
  content_sha256      varchar2(64 char) not null,
  content_uri         varchar2(1000 char) not null,
  mime_type           varchar2(255 char) not null,
  original_filename   varchar2(500 char),
  byte_size           number not null,
  source_modified_on  timestamp with time zone,
  created_by          varchar2(128 char) default coalesce(
                        sys_context('apex$session', 'app_user'),
                        sys_context('userenv', 'proxy_user'),
                        sys_context('userenv', 'session_user'),
                        user
                      ) not null,
  created_on          timestamp with time zone default systimestamp not null,
  updated_by          varchar2(128 char) default coalesce(
                        sys_context('apex$session', 'app_user'),
                        sys_context('userenv', 'proxy_user'),
                        sys_context('userenv', 'session_user'),
                        user
                      ) not null,
  updated_on          timestamp with time zone default systimestamp not null,
  row_version         number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_document_versions purge;

--changeset clive:create_table_orac_core_knowledge_ingestion_requests context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_INGESTION_REQUESTS';
create table orac_core.knowledge_ingestion_requests
(
  ingestion_request_id    number generated by default on null as identity not null,
  source_object_id        number not null,
  document_id             number not null,
  document_version_id     number not null,
  processing_profile_code varchar2(100 char),
  processing_instruction  clob,
  status_code             varchar2(50 char) default 'QUEUED' not null,
  stage_code              varchar2(50 char) default 'SUBMITTED' not null,
  attempts                number default 0 not null,
  max_attempts            number default 5 not null,
  next_attempt_on         timestamp with time zone default systimestamp not null,
  lease_owner             varchar2(500 char),
  lease_token             varchar2(64 char),
  lease_expires_on        timestamp with time zone,
  last_error_code         varchar2(100 char),
  last_error_message      clob,
  completed_on            timestamp with time zone,
  created_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  created_on              timestamp with time zone default systimestamp not null,
  updated_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  updated_on              timestamp with time zone default systimestamp not null,
  row_version             number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_ingestion_requests purge;

--changeset clive:create_table_orac_core_knowledge_extractions context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_EXTRACTIONS';
create table orac_core.knowledge_extractions
(
  extraction_id       number generated by default on null as identity not null,
  document_version_id number not null,
  extractor_code      varchar2(100 char) not null,
  extractor_version   varchar2(100 char) not null,
  text_sha256         varchar2(64 char) not null,
  extracted_text      clob not null,
  created_by          varchar2(128 char) default coalesce(
                        sys_context('apex$session', 'app_user'),
                        sys_context('userenv', 'proxy_user'),
                        sys_context('userenv', 'session_user'),
                        user
                      ) not null,
  created_on          timestamp with time zone default systimestamp not null,
  updated_by          varchar2(128 char) default coalesce(
                        sys_context('apex$session', 'app_user'),
                        sys_context('userenv', 'proxy_user'),
                        sys_context('userenv', 'session_user'),
                        user
                      ) not null,
  updated_on          timestamp with time zone default systimestamp not null,
  row_version         number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_extractions purge;

--changeset clive:create_table_orac_core_knowledge_chunk_sets context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_CHUNK_SETS';
create table orac_core.knowledge_chunk_sets
(
  chunk_set_id      number generated by default on null as identity not null,
  extraction_id     number not null,
  chunker_code      varchar2(100 char) not null,
  chunker_version   varchar2(100 char) not null,
  chunk_size_tokens number not null,
  overlap_tokens    number default 0 not null,
  created_by        varchar2(128 char) default coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  created_on        timestamp with time zone default systimestamp not null,
  updated_by        varchar2(128 char) default coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  updated_on        timestamp with time zone default systimestamp not null,
  row_version       number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_chunk_sets purge;

--changeset clive:create_table_orac_core_knowledge_chunks context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_CHUNKS';
create table orac_core.knowledge_chunks
(
  chunk_id       number generated by default on null as identity not null,
  chunk_set_id   number not null,
  chunk_no       number not null,
  span_start     number not null,
  span_end       number not null,
  token_count    number default 0 not null,
  content_sha256 varchar2(64 char) not null,
  chunk_text     clob not null,
  created_by     varchar2(128 char) default coalesce(
                   sys_context('apex$session', 'app_user'),
                   sys_context('userenv', 'proxy_user'),
                   sys_context('userenv', 'session_user'),
                   user
                 ) not null,
  created_on     timestamp with time zone default systimestamp not null,
  updated_by     varchar2(128 char) default coalesce(
                   sys_context('apex$session', 'app_user'),
                   sys_context('userenv', 'proxy_user'),
                   sys_context('userenv', 'session_user'),
                   user
                 ) not null,
  updated_on     timestamp with time zone default systimestamp not null,
  row_version    number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_chunks purge;

--changeset clive:create_table_orac_core_knowledge_embedding_models context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_EMBEDDING_MODELS';
create table orac_core.knowledge_embedding_models
(
  embedding_model_id number generated by default on null as identity not null,
  provider_code      varchar2(100 char) not null,
  model_name         varchar2(255 char) not null,
  model_revision     varchar2(100 char) not null,
  dimensions         number not null,
  distance_metric    varchar2(50 char) not null,
  normalisation      varchar2(50 char) not null,
  active_yn          varchar2(1 char) default 'Y' not null,
  created_by         varchar2(128 char) default coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  created_on         timestamp with time zone default systimestamp not null,
  updated_by         varchar2(128 char) default coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  updated_on         timestamp with time zone default systimestamp not null,
  row_version        number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_embedding_models purge;

--changeset clive:create_table_orac_core_knowledge_chunk_embeddings context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_CHUNK_EMBEDDINGS';
create table orac_core.knowledge_chunk_embeddings
(
  chunk_embedding_id   number generated by default on null as identity not null,
  chunk_id             number not null,
  embedding_model_id   number not null,
  embedding_text_sha256 varchar2(64 char) not null,
  embedding_vector     clob not null,
  created_by           varchar2(128 char) default coalesce(
                         sys_context('apex$session', 'app_user'),
                         sys_context('userenv', 'proxy_user'),
                         sys_context('userenv', 'session_user'),
                         user
                       ) not null,
  created_on           timestamp with time zone default systimestamp not null,
  updated_by           varchar2(128 char) default coalesce(
                         sys_context('apex$session', 'app_user'),
                         sys_context('userenv', 'proxy_user'),
                         sys_context('userenv', 'session_user'),
                         user
                       ) not null,
  updated_on           timestamp with time zone default systimestamp not null,
  row_version          number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_chunk_embeddings purge;

--changeset clive:create_table_orac_core_knowledge_ingestion_events context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'KNOWLEDGE_INGESTION_EVENTS';
create table orac_core.knowledge_ingestion_events
(
  ingestion_event_id   number generated by default on null as identity not null,
  ingestion_request_id number not null,
  event_type           varchar2(100 char) not null,
  event_message        clob,
  event_ts             timestamp with time zone default systimestamp not null,
  created_by           varchar2(128 char) default coalesce(
                         sys_context('apex$session', 'app_user'),
                         sys_context('userenv', 'proxy_user'),
                         sys_context('userenv', 'session_user'),
                         user
                       ) not null,
  created_on           timestamp with time zone default systimestamp not null
)
logging
no inmemory;
--rollback drop table orac_core.knowledge_ingestion_events purge;
