-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac_core.messages
(
  message_id      number generated by default on null as identity not null,
  conversation_id number not null,
  turn_index      number not null,
  role            varchar2(20 byte) not null,
  message_type    varchar2 (30 char), 
  content         json not null,
  tokens_used     number,
  meta            json,
  llm_id          number,
  created_on      timestamp default systimestamp not null,
  created_by      varchar2(128 byte) default coalesce(
                    sys_context('apex$session', 'app_user'),
                    sys_context('userenv', 'proxy_user'),
                    sys_context('userenv', 'session_user'),
                    user
                  ) not null,
  updated_on      timestamp,
  updated_by      varchar2(128 byte),
  row_version     number default 1 not null
)
;
