-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac_core.message_embeddings
(
  emb_id             number generated by default on null as identity not null,
  message_id         number not null,
  chunk_index        number default 1 not null,
  span_start         number,
  span_end           number,
  lossless_text      clob not null,
  content_snapshot   json,
  embedding          vector(*, *) not null,
  embedding_model    varchar2(100 char) not null,
  embedding_provider varchar2(100 char) default on null 'oracle' not null,
  distance_metric    varchar2(16 char) default 'COSINE' not null,
  tokens_used        number,
  created_on         timestamp default systimestamp not null,
  created_by         varchar2(128 char) default sys_context('userenv', 'session_user') not null,
  updated_on         timestamp,
  updated_by         varchar2(128 char),
  row_version        number default 1 not null
)
;
