-- __author__: clive
-- __date__: 2026-05-23
-- __description__: reusable LLM generation presets for Orac model requests


create table orac_core.model_generation_presets
(
  model_preset_id   number generated by default on null as identity not null,
  model_preset_code varchar2(50 char) not null,
  model_preset_name varchar2(100 char) not null,
  description       varchar2(4000 char),
  temperature       number,
  top_p             number,
  top_k             number,
  repeat_penalty    number,
  num_predict       number,
  seed              number,
  is_system_preset  varchar2(1 char) default 'Y' not null,
  is_active         varchar2(1 char) default 'Y' not null,
  created_by        varchar2(255 char) default on null coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  created_on        timestamp with local time zone default on null systimestamp not null,
  updated_by        varchar2(255 char),
  updated_on        timestamp with local time zone,
  row_version       number default 1 not null
)
;
