--liquibase formatted sql

--changeset clive:create_table_orac_core_table_orac_search_queries context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'ORAC_SEARCH_QUERIES';
-- __author__: clive
-- __date__: 2026-05-26
-- __description__: stores explicit internet search requests for retrieval cache


create table orac_core.orac_search_queries
(
  search_query_id   number generated by default on null as identity not null,
  query_text        varchar2(4000 char) not null,
  trigger_phrase    varchar2(128 char),
  provider_name    varchar2(64 char) not null,
  max_results       number,
  created_on        timestamp default systimestamp not null,
  created_by        varchar2(128 char) default coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  updated_on        timestamp,
  updated_by        varchar2(128 char),
  row_version       number default 1 not null
)
;


--rollback drop table orac_core.orac_search_queries purge;
