-- __author__: clive
-- __date__: 2026-05-26
-- __description__: stores conservatively fetched source evidence for retrieval cache


create table orac_core.orac_fetched_sources
(
  fetched_source_id   number generated by default on null as identity not null,
  search_result_id    number not null,
  url                 varchar2(2048 char) not null,
  title               varchar2(1000 char),
  source_name         varchar2(256 char),
  content_type        varchar2(128 char),
  fetched_text        varchar2(4000 char),
  excerpt             varchar2(2000 char),
  byte_count          number,
  fetched_on          timestamp default systimestamp not null,
  created_by          varchar2(128 char) default coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  updated_on          timestamp,
  updated_by          varchar2(128 char),
  row_version         number default 1 not null
)
;

