--liquibase formatted sql

--changeset clive:create_table_orac_core_table_plugin_registry context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'PLUGIN_REGISTRY';
-- __author__: clive
-- __date__: 2026-06-07
-- __description__: current installation and activation state for Orac plugins

create table orac_core.plugin_registry
(
  plugin_registry_id       number generated by default on null as identity not null,
  plugin_id                varchar2(128 char) not null,
  plugin_name              varchar2(256 char) not null,
  plugin_version           varchar2(64 char) not null,
  runtime_mode             varchar2(32 char) not null,
  manifest_hash            varchar2(64 char) not null,
  package_hash             varchar2(64 char) not null,
  install_source_type      varchar2(32 char) not null,
  install_source_ref       varchar2(1000 char) not null,
  installed_path           varchar2(1000 char),
  config_path              varchar2(1000 char),
  capabilities_summary     json,
  entitlements_summary     json,
  database_schemas_summary json,
  dependency_declarations  json,
  dependency_fingerprint   varchar2(64 char) not null,
  install_status           varchar2(64 char) not null,
  configuration_status     varchar2(64 char) not null,
  dependency_status        varchar2(64 char) not null,
  database_status          varchar2(64 char) not null,
  readiness_status         varchar2(64 char) not null,
  enabled                  varchar2(1 char) default 'N' not null,
  last_error_code          varchar2(128 char),
  last_error_message       varchar2(2000 char),
  created_on               timestamp default systimestamp not null,
  created_by               varchar2(128 char) default coalesce(
                             sys_context('apex$session', 'app_user'),
                             sys_context('userenv', 'proxy_user'),
                             sys_context('userenv', 'session_user'),
                             user
                           ) not null,
  updated_on               timestamp,
  updated_by               varchar2(128 char),
  row_version              number default 1 not null
);

--rollback drop table orac_core.plugin_registry purge;
