-- __author__: clive
-- __date__: 2026-05-25
-- __description__: plugin audit lifecycle event table


create table orac_core.plugin_audit_events
(
  plugin_audit_event_id number generated by default on null as identity not null,
  plugin_invocation_id  number not null,
  event_type            varchar2(64 char) not null,
  event_status          varchar2(64 char),
  event_message         varchar2(1000 char),
  policy_decision       varchar2(64 char),
  confirmation_id       varchar2(128 char),
  execution_status      varchar2(64 char),
  failure_type          varchar2(128 char),
  failure_message       varchar2(1000 char),
  event_payload_json    json,
  created_on            timestamp default systimestamp not null,
  created_by            varchar2(128 char) default coalesce(
                          sys_context('apex$session', 'app_user'),
                          sys_context('userenv', 'proxy_user'),
                          sys_context('userenv', 'session_user'),
                          user
                        ) not null,
  updated_on            timestamp,
  updated_by            varchar2(128 char),
  row_version           number default 1 not null
)
;
