--liquibase formatted sql

--changeset clive:create_table_orac_core_table_plugin_services context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'PLUGIN_SERVICES';
-- __author__: clive
-- __date__: 2026-07-02
-- __description__: Orac-owned plugin service lifecycle state and lease metadata

create table orac_core.plugin_services
(
  plugin_service_id number generated by default on null as identity not null,
  plugin_id         varchar2(128 char) not null,
  service_code      varchar2(128 char) not null,
  service_name      varchar2(256 char),
  entry_point       varchar2(512 char) not null,
  execution_model   varchar2(32 char) not null,
  manifest_policy   varchar2(32 char) not null,
  policy_override   varchar2(32 char),
  current_state     varchar2(32 char) default 'registered' not null,
  owner_id          varchar2(512 char),
  lease_token       varchar2(64 char),
  lease_expires_on  timestamp,
  last_started_on   timestamp,
  last_heartbeat_on timestamp,
  last_tick_on      timestamp,
  last_error_message varchar2(2000 char),
  created_on        timestamp default systimestamp not null,
  created_by        varchar2(128 char) default coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  updated_on        timestamp,
  updated_by        varchar2(128 char),
  row_version       number default 1 not null
);

--rollback drop table orac_core.plugin_services purge;
