-- __author__: clive
-- __date__: 2026-05-25
-- __description__: plugin invocation audit summary table


create table orac_core.plugin_invocations
(
  plugin_invocation_id number generated by default on null as identity not null,
  request_id           varchar2(128 char),
  correlation_id       varchar2(128 char),
  turn_id              varchar2(128 char),
  conversation_id      number,
  message_id           number,
  user_id              number,
  plugin_id            varchar2(128 char) not null,
  plugin_name          varchar2(256 char) not null,
  action_type          varchar2(64 char) not null,
  capabilities         json,
  entitlements         json,
  policy_decision      varchar2(64 char),
  policy_reason        varchar2(1000 char),
  confirmation_id      varchar2(128 char),
  confirmation_status  varchar2(64 char),
  execution_status     varchar2(64 char) not null,
  timeout_seconds      number,
  failure_type         varchar2(128 char),
  failure_message      varchar2(1000 char),
  provenance_json      json,
  created_on           timestamp default systimestamp not null,
  created_by           varchar2(128 char) default coalesce(
                         sys_context('apex$session', 'app_user'),
                         sys_context('userenv', 'proxy_user'),
                         sys_context('userenv', 'session_user'),
                         user
                       ) not null,
  updated_on           timestamp,
  updated_by           varchar2(128 char),
  row_version          number default 1 not null
)
;
