-- __author__: clive
-- __date__: 2026-06-20
-- __description__: registry of plugin-supplied APEX applications

create table orac_core.plugin_apex_apps
(
  plugin_apex_app_id      number generated by default on null as identity not null,
  plugin_id               varchar2(128 char) not null,
  plugin_version          varchar2(64 char) not null,
  app_alias               varchar2(128 char) not null,
  workspace               varchar2(128 char) default 'ORAC' not null,
  parsing_schema          varchar2(128 char) default 'ORAC_APX_PUB' not null,
  app_export              varchar2(1000 char) not null,
  declared_application_id number,
  installed_app_id        number,
  entry_page_id           number default 1 not null,
  label                   varchar2(256 char) not null,
  description             varchar2(1000 char),
  required_roles          json,
  icon                    varchar2(128 char),
  card_title              varchar2(256 char),
  card_subtitle           varchar2(512 char),
  install_status          varchar2(64 char) not null,
  install_log             clob,
  last_error_message      varchar2(4000 char),
  enabled                 varchar2(1 char) default 'Y' not null,
  created_on              timestamp default systimestamp not null,
  created_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  updated_on              timestamp,
  updated_by              varchar2(128 char),
  row_version             number default 1 not null
);
