-- __author__: clive
-- __date__: 2026-06-03
-- __description__: plugin database deployment state table


create table orac_core.plugin_db_deployments
(
  plugin_db_deployment_id number generated by default on null as identity not null,
  plugin_id               varchar2(128 char) not null,
  plugin_version          varchar2(64 char) not null,
  schema_name             varchar2(128 char) not null,
  deployment_checksum     varchar2(64 char) not null,
  deployment_status       varchar2(64 char) not null,
  started_on              timestamp default systimestamp not null,
  completed_on            timestamp,
  error_message           varchar2(1000 char),
  log_path                varchar2(1000 char),
  created_on              timestamp default systimestamp not null,
  created_by              varchar2(128 char) default coalesce(
                            sys_context('apex$session', 'app_user'),
                            sys_context('userenv', 'proxy_user'),
                            sys_context('userenv', 'session_user'),
                            user
                          ) not null,
  updated_on              timestamp,
  updated_by              varchar2(128 char),
  row_version             number default 1 not null
)
;
