--liquibase formatted sql

--changeset clive:create_table_orac_core_table_preference_definitions context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'PREFERENCE_DEFINITIONS';
-- __author__: clive
-- __date__: 2026-04-27
-- __description__: preference metadata definitions for validation, display, and LOV behaviour


create table orac_core.preference_definitions
(
  pref_def_id        number generated by default on null as identity not null,
  pref_key           varchar2(100 byte) not null,
  display_label      varchar2(200 byte) not null,
  description        varchar2(1000 byte),
  value_type         varchar2(30 byte) not null,
  control_type       varchar2(30 byte) not null,
  lov_type           varchar2(30 byte),
  lov_query          clob,
  static_lov_code    varchar2(100 byte),
  default_value      json,
  min_number         number,
  max_number         number,
  min_length         number,
  max_length         number,
  regex_pattern      varchar2(1000 byte),
  is_required        varchar2(1 byte) default 'N' not null,
  is_user_editable   varchar2(1 byte) default 'Y' not null,
  display_sequence   number default 10 not null,
  category           varchar2(100 byte),
  help_text          varchar2(2000 byte),
  is_active          varchar2(1 byte) default 'Y' not null,
  created_on         timestamp default on null systimestamp not null,
  created_by         varchar2(128 byte) default on null coalesce(
                       sys_context('apex$session', 'app_user'),
                       sys_context('userenv', 'proxy_user'),
                       sys_context('userenv', 'session_user'),
                       user
                     ) not null,
  updated_on         timestamp,
  updated_by         varchar2(128 byte),
  row_version        number default 1 not null
)
;

--rollback drop table orac_core.preference_definitions purge;
