--liquibase formatted sql

--changeset clive:create_table_orac_core_project_registry context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'PROJECT_REGISTRY';
-- __author__: clive
-- __date__: 2026-07-11
-- __description__: core registry of project codes available as ingestion targets

create table orac_core.project_registry
(
  project_id   number generated by default on null as identity not null,
  project_code varchar2(100 char) not null,
  display_name varchar2(200 char) not null,
  description  varchar2(1000 char),
  active_yn    varchar2(1 char) default 'Y' not null,
  created_by   varchar2(128 char) default on null coalesce(
                 sys_context('apex$session', 'app_user'),
                 sys_context('userenv', 'proxy_user'),
                 sys_context('userenv', 'session_user'),
                 user
               ) not null,
  created_on   timestamp with local time zone default on null systimestamp not null,
  updated_by   varchar2(128 char),
  updated_on   timestamp with local time zone,
  row_version  number default 1 not null
);

--rollback drop table orac_core.project_registry purge;
