--liquibase formatted sql

--changeset clive:create_table_orac_core_rag_usage_privileges context:core labels:core stripComments:false
--preconditions onFail:HALT onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = 'ORAC_CORE' and table_name = 'RAG_USAGE_PRIVILEGES';
-- __author__: clive
-- __date__: 2026-07-20
-- __description__: auditable historical RAG usage privilege grants

create table orac_core.rag_usage_privileges
(
  rag_usage_privilege_id number generated by default on null as identity not null,
  user_id                number not null,
  knowledge_scope_id     number not null,
  privilege_code         varchar2(30 char) default 'USE' not null,
  active_yn              varchar2(1 char) default 'Y' not null,
  effective_on           timestamp with time zone default systimestamp not null,
  expires_on             timestamp with time zone,
  granted_on             timestamp with time zone default systimestamp not null,
  granted_by             varchar2(128 char) not null,
  grant_reason_code      varchar2(100 char) not null,
  revoked_on             timestamp with time zone,
  revoked_by             varchar2(128 char),
  revoke_reason_code     varchar2(100 char),
  created_by             varchar2(128 char) default coalesce(
                           sys_context('apex$session', 'app_user'),
                           sys_context('userenv', 'proxy_user'),
                           sys_context('userenv', 'session_user'),
                           user
                         ) not null,
  created_on             timestamp with time zone default systimestamp not null,
  updated_by             varchar2(128 char) default coalesce(
                           sys_context('apex$session', 'app_user'),
                           sys_context('userenv', 'proxy_user'),
                           sys_context('userenv', 'session_user'),
                           user
                         ) not null,
  updated_on             timestamp with time zone default systimestamp not null,
  row_version            number default 1 not null
)
logging
no inmemory;
--rollback drop table orac_core.rag_usage_privileges purge;
