-- __author__: clive
-- __date__: 2026-04-27
-- __description__: curated canonical timezone catalogue for user-facing LOVs


create table orac_core.timezones
(
  timezone_id       number generated by default on null as identity not null,
  tz_name           varchar2(100 byte) not null,
  display_label     varchar2(200 byte) not null,
  region_group      varchar2(50 byte) not null,
  display_sequence  number default 10 not null,
  is_active         varchar2(1 byte) default 'Y' not null,
  created_on        timestamp default on null systimestamp not null,
  created_by        varchar2(128 byte) default on null coalesce(
                      sys_context('apex$session', 'app_user'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null,
  updated_on        timestamp,
  updated_by        varchar2(128 byte),
  row_version       number default 1 not null
)
;
