-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac.user_prompt_elements
(
  element_id     number generated by default on null as identity not null,
  user_id        number not null,
  category_code  varchar2(50 byte) not null,
  prompt_element clob not null,
  weight_score   number(5,2) default 1 not null,
  is_enabled     char(1 byte) default 'Y' not null,
  created_on     timestamp default on null systimestamp not null,
  created_by     varchar2(128 byte) default on null sys_context('userenv', 'session_user') not null,
  updated_on     timestamp,
  updated_by     varchar2(128 byte),
  row_version    number default 1 not null
)
;
