-- __author__: clive
-- __date__: 2026-03-21
-- __description__: generated/synchronised by split_ddl; one object per file


create table orac_core.user_preferences
(
  pref_id     number generated by default on null as identity not null,
  user_id     number not null,
  pref_key    varchar2(100 byte) not null,
  pref_value  json,
  value_type  varchar2(8 byte) default 'string' not null,
  created_on  timestamp default on null systimestamp not null,
  created_by  varchar2(128 byte) default on null coalesce(
                sys_context('apex$session', 'app_user'),
                sys_context('userenv', 'proxy_user'),
                sys_context('userenv', 'session_user'),
                user
              ) not null,
  updated_on  timestamp,
  updated_by  varchar2(128 byte),
  row_version number default 1 not null
)
;
