--liquibase formatted sql
declare
  l_count number;
begin
  select count(*)
    into l_count
    from all_tables
   where owner = 'ORAC_DROPBOX'
     and table_name = 'DROP_JOB';

  if l_count = 0
  then
    execute immediate q'~
create table orac_dropbox.drop_job
(
  drop_job_id                  number generated by default on null as identity not null,
  drop_location_id             number not null,
  source_path                  varchar2(1000 char) not null,
  source_filename              varchar2(500 char) not null,
  source_hash                  varchar2(128 char) not null,
  source_size_bytes            number not null,
  source_mtime                 timestamp with time zone not null,
  detected_on                  timestamp with time zone default systimestamp not null,
  stable_on                    timestamp with time zone,
  status_code                  varchar2(50 char) not null,
  effective_scope_type         varchar2(50 char) not null,
  effective_scope_key          varchar2(200 char) not null,
  effective_processing_profile varchar2(100 char) not null,
  effective_instruction        clob,
  error_message                clob,
  document_id                  number,
  started_on                   timestamp with time zone,
  completed_on                 timestamp with time zone,
  created_on                   timestamp with time zone default systimestamp not null,
  created_by                   varchar2(128 char) default coalesce(
                                 sys_context('userenv', 'client_identifier'),
                                 sys_context('userenv', 'proxy_user'),
                                 sys_context('userenv', 'session_user'),
                                 user
                               ) not null,
  updated_on                   timestamp with time zone,
  updated_by                   varchar2(128 char),
  row_version                  number default 1 not null
)
logging
no inmemory
    ~';
  end if;
end;
/
