--liquibase formatted sql
declare
  l_count number;
begin
  select count(*)
    into l_count
    from all_tables
   where owner = 'ORAC_DROPBOX'
     and table_name = 'DROP_LOCATION';

  if l_count = 0
  then
    execute immediate q'~
create table orac_dropbox.drop_location
(
  drop_location_id       number generated by default on null as identity not null,
  location_code          varchar2(100 char) not null,
  display_name           varchar2(200 char) not null,
  path                   varchar2(1000 char) not null,
  enabled_yn             varchar2(1 char) default 'Y' not null,
  target_scope_type      varchar2(50 char) not null,
  target_scope_key       varchar2(200 char) not null,
  processing_profile     varchar2(100 char) not null,
  processing_instruction clob,
  allowed_extensions     varchar2(1000 char),
  ignore_patterns        varchar2(1000 char),
  recursive_yn           varchar2(1 char) default 'N' not null,
  move_processed_yn      varchar2(1 char) default 'Y' not null,
  processed_path         varchar2(1000 char),
  failed_path            varchar2(1000 char),
  max_file_size_mb       number,
  stability_seconds      number default 10 not null,
  created_on             timestamp with time zone default systimestamp not null,
  created_by             varchar2(128 char) default coalesce(
                           sys_context('userenv', 'client_identifier'),
                           sys_context('userenv', 'proxy_user'),
                           sys_context('userenv', 'session_user'),
                           user
                         ) not null,
  updated_on             timestamp with time zone,
  updated_by             varchar2(128 char),
  row_version            number default 1 not null
)
logging
no inmemory
    ~';
  end if;
end;
/
