--liquibase formatted sql
declare
  l_count number;
begin
  select count(*)
    into l_count
    from all_tables
   where owner = 'ORAC_DROPBOX'
     and table_name = 'DROP_JOB_EVENT';

  if l_count = 0
  then
    execute immediate q'~
create table orac_dropbox.drop_job_event
(
  drop_job_event_id number generated by default on null as identity not null,
  drop_job_id       number not null,
  event_ts          timestamp with time zone default systimestamp not null,
  event_type        varchar2(50 char) not null,
  event_message     clob,
  created_on        timestamp with time zone default systimestamp not null,
  created_by        varchar2(128 char) default coalesce(
                      sys_context('userenv', 'client_identifier'),
                      sys_context('userenv', 'proxy_user'),
                      sys_context('userenv', 'session_user'),
                      user
                    ) not null
)
logging
no inmemory
    ~';
  end if;
end;
/
